export interface BulkMaterialHandlingService {
  id: string;
  slug: string;
  title: string;
  badge: string;
  image: string;
  shortDescription: string;
  description: string[];
  applications: string[];
  keyAnalyses: string[];
  deliverables: string[];
  keyBenefits: string[];
}

export const BULK_MATERIAL_HANDLING_SERVICES: BulkMaterialHandlingService[] = [
  {
    id: "01",
    slug: "bulk-material-and-particle-flow-analysis",
    title: "Bulk Material & Particle Flow Analysis",
    badge: "BULK SOLIDS & DEM",
    image: "/images/cfd-engineering/bulk-material-handling/service_01.jpg",
    shortDescription:
      "Advanced CFD-DEM particle flow simulation to evaluate bulk solids movement, segregation, impact velocities, build-up, and transfer point capacity.",
    description: [
      "Reliable bulk material flow is essential for maintaining stable throughput across material handling and storage systems. Variations in particle size, moisture, material properties, equipment geometry, and operating conditions can result in segregation, material build-up, uneven discharge, excessive impact, spillage, and flow restrictions.",
      "MACPROTEC applies advanced particle-flow simulation, including CFD-DEM and DEM-based analysis where appropriate, to evaluate the movement and interaction of bulk solids throughout handling systems. Our studies provide detailed insight into particle trajectories, material distribution, impact behavior, and flow patterns, helping optimize equipment geometry, improve material transfer, and reduce operational problems.",
    ],
    applications: [
      "Transfer Chutes & Transfer Points",
      "Hoppers & Bins",
      "Storage Silos",
      "Conveyor Loading & Discharge",
      "Feeders",
      "Loading & Unloading Systems",
      "Material Distribution Systems",
      "Bulk Solid Handling Equipment",
    ],
    keyAnalyses: [
      "Particle trajectory and bulk material flow analysis",
      "Material velocity and distribution assessment",
      "Particle segregation and size distribution behavior",
      "Material build-up and stagnant-zone identification",
      "Chute trajectory and transfer performance analysis",
      "Hopper, bin, and silo discharge behavior",
      "Particle impact velocity and impact-zone assessment",
      "Material spillage and uncontrolled trajectory investigation",
      "Flow distribution to downstream equipment",
      "Influence of particle size, moisture, and material properties",
      "Equipment geometry and operating-condition optimization",
    ],
    deliverables: [
      "Particle trajectory and material-flow visualizations",
      "Material velocity and distribution maps",
      "Build-up and stagnant-zone identification",
      "Segregation and discharge-performance assessment",
      "Particle impact and high-wear zone identification",
      "Chute and transfer-point performance evaluation",
      "Comparative assessment of design alternatives",
      "Engineering recommendations for material-flow optimization",
    ],
    keyBenefits: [
      "Improve bulk material flow and transfer efficiency",
      "Reduce blockages, build-up, and material hang-up",
      "Minimize segregation and uneven material distribution",
      "Reduce spillage and material losses",
      "Minimize excessive particle impact and equipment wear",
      "Improve conveyor loading and downstream feed uniformity",
      "Increase handling capacity and system reliability",
      "Support new equipment design and existing-system modifications",
      "Reduce maintenance requirements and unplanned downtime",
    ],
  },
  {
    id: "02",
    slug: "pneumatic-conveying-and-gas-solid-flow-analysis",
    title: "Pneumatic Conveying & Gas-Solid Flow Analysis",
    badge: "PNEUMATIC TRANSPORT",
    image: "/images/cfd-engineering/bulk-material-handling/service_02.jpg",
    shortDescription:
      "Simulation of dilute and dense phase gas-solid transport to optimize conveying velocity, pressure drop, particle deposition, and bend erosion.",
    description: [
      "Pneumatic conveying systems are widely used for the enclosed transport of powders, granules, and fine bulk materials across industrial handling facilities. Inadequate conveying velocity, poor solids distribution, excessive pressure losses, particle deposition, and unstable gas-solid flow can result in pipeline blockage, excessive wear, reduced conveying capacity, and high energy consumption.",
      "MACPROTEC applies advanced CFD and particle-flow modeling to simulate gas-solid transport throughout pneumatic conveying systems. Our analyses evaluate airflow, particle trajectories, solids concentration, pressure losses, and particle-wall interactions to optimize system geometry and operating conditions for reliable, efficient, and controlled material transport.",
    ],
    applications: [
      "Pneumatic Conveying Lines",
      "Dense & Dilute Phase Systems",
      "Powder & Fine Material Transport",
      "Silo Feeding & Discharge",
      "Dust Return Systems",
      "Material Distribution Networks",
      "Bends, Tees & Diverters",
      "Loading & Transfer Systems",
    ],
    keyAnalyses: [
      "Gas-solid flow distribution analysis",
      "Particle velocity and trajectory prediction",
      "Pressure drop and system resistance evaluation",
      "Minimum conveying velocity assessment",
      "Solids loading and concentration distribution",
      "Particle deposition and accumulation analysis",
      "Pipeline plugging and blockage risk assessment",
      "Particle-wall interaction and erosion prediction",
      "Flow behavior through bends, tees, and diverters",
      "Flow splitting and material distribution at branches",
      "Dense and dilute phase conveying performance",
      "Operating condition and pipeline geometry optimization",
    ],
    deliverables: [
      "Gas velocity and pressure contour visualizations",
      "Particle trajectory and solids concentration maps",
      "Conveying pressure drop and performance assessment",
      "Deposition and blockage-risk identification",
      "Erosion and particle-impact assessment",
      "Conveying velocity and solids-loading evaluation",
      "Flow distribution assessment at branches and outlets",
      "Comparative evaluation of design and operating scenarios",
      "Engineering recommendations for system optimization",
    ],
    keyBenefits: [
      "Improve conveying capacity and system reliability",
      "Reduce material deposition and pipeline blockage",
      "Minimize pressure losses and conveying energy consumption",
      "Improve solids distribution throughout the conveying network",
      "Reduce erosion and premature pipeline wear",
      "Maintain stable material transport across varying operating conditions",
      "Improve performance of bends, branches, and distribution points",
      "Support conveying-system debottlenecking and capacity expansion",
      "Reduce maintenance requirements and unplanned downtime",
    ],
  },
  {
    id: "03",
    slug: "chute-and-transfer-point-flow-analysis",
    title: "Chute & Transfer Point Flow Analysis",
    badge: "TRANSFER CHUTES",
    image: "/images/cfd-engineering/bulk-material-handling/service_03.jpg",
    shortDescription:
      "CFD-DEM modeling of material movement through transfer chutes, crusher feed chutes, and diverters to optimize stream centering and eliminate belt damage.",
    description: [
      "Chutes and transfer points are critical interfaces in bulk material handling systems, where poor material trajectory, uncontrolled impact, flow restriction, or improper loading can lead to blockages, spillage, excessive dust generation, accelerated wear, and conveyor belt damage. Material behavior can vary significantly with particle size, moisture content, feed rate, and operating conditions.",
      "MACPROTEC applies advanced particle-flow simulation, including CFD-DEM and DEM modeling where appropriate, to analyze material movement through chutes and conveyor transfer points. Our simulations evaluate particle trajectories, impact zones, material velocities, flow distribution, and air-particle interactions to develop reliable transfer arrangements with improved flow control and reduced wear.",
    ],
    applications: [
      "Conveyor Transfer Points",
      "Transfer & Discharge Chutes",
      "Crusher Feed Chutes",
      "Screen Feed & Discharge Chutes",
      "Conveyor Loading Zones",
      "Diverter & Distribution Chutes",
      "Stockpile Transfer Systems",
      "Loading & Unloading Stations",
    ],
    keyAnalyses: [
      "Material trajectory and particle-flow analysis",
      "Chute inlet and discharge flow behavior",
      "Particle velocity and impact-energy assessment",
      "Material build-up and blockage identification",
      "Dead-zone and stagnant-material analysis",
      "Conveyor belt loading and material centering",
      "Particle segregation and flow distribution assessment",
      "Spillage and uncontrolled trajectory investigation",
      "Air entrainment and dust-generation potential",
      "Impact, abrasion, and wear-prone zone identification",
      "Chute geometry and liner configuration assessment",
      "Performance evaluation at different material feed rates",
    ],
    deliverables: [
      "Particle trajectory and material-flow visualizations",
      "Material velocity and distribution maps",
      "Impact and high-wear zone identification",
      "Build-up and blockage-risk assessment",
      "Conveyor loading and material-centering evaluation",
      "Spillage and dust-generation assessment",
      "Comparative evaluation of chute geometries",
      "Engineering recommendations for transfer-point optimization",
    ],
    keyBenefits: [
      "Improve material transfer efficiency and flow continuity",
      "Reduce chute blockage and material build-up",
      "Minimize spillage and uncontrolled material discharge",
      "Reduce impact forces and equipment wear",
      "Improve material centering and conveyor belt loading",
      "Reduce dust generation at transfer points",
      "Increase chute and liner service life",
      "Support higher throughput and system debottlenecking",
      "Reduce maintenance requirements and unplanned downtime",
    ],
  },
  {
    id: "04",
    slug: "hopper-bin-and-silo-flow-analysis",
    title: "Hopper, Bin & Silo Flow Analysis",
    badge: "SILO & HOPPER FLOW",
    image: "/images/cfd-engineering/bulk-material-handling/service_04.jpg",
    shortDescription:
      "DEM and CFD-DEM simulation of filling, storage, mass-flow vs funnel-flow patterns, arching, ratholing, and feeder interaction in storage silos.",
    description: [
      "Hoppers, bins, and silos are critical for the reliable storage, feeding, and discharge of bulk materials. Variations in particle size, moisture, cohesiveness, wall friction, and equipment geometry can cause flow restrictions, arching, ratholing, segregation, uneven discharge, and stagnant material zones, resulting in unstable downstream operation and reduced handling capacity.",
      "MACPROTEC applies advanced particle-flow simulation, including DEM and CFD-DEM where appropriate, to evaluate bulk material behavior during filling, storage, and discharge. Our analyses provide detailed insight into particle movement, flow patterns, stress distribution, segregation, and discharge characteristics, helping optimize equipment geometry and operating conditions for reliable and consistent material flow.",
    ],
    applications: [
      "Storage Silos",
      "Feed & Surge Bins",
      "Process Hoppers",
      "Buffer & Day Bins",
      "Dosing Hoppers",
      "Discharge Cones",
      "Silo Feeding Systems",
      "Bulk Material Storage Systems",
    ],
    keyAnalyses: [
      "Filling and discharge flow behavior",
      "Mass-flow and funnel-flow pattern assessment",
      "Arching and bridging tendency analysis",
      "Ratholing and stagnant-zone identification",
      "Particle segregation and size distribution assessment",
      "Discharge rate and flow uniformity evaluation",
      "Hopper angle and outlet-size optimization",
      "Wall friction and material interaction assessment",
      "Asymmetric and eccentric discharge analysis",
      "Particle residence time and material turnover",
      "Influence of moisture and material properties",
      "Feeder interaction and discharge performance evaluation",
    ],
    deliverables: [
      "Particle-flow and discharge visualizations",
      "Material velocity and distribution maps",
      "Mass-flow and funnel-flow assessment",
      "Arching, ratholing, and stagnant-zone identification",
      "Segregation and residence-time assessment",
      "Discharge capacity and flow-uniformity evaluation",
      "Comparative assessment of hopper and outlet configurations",
      "Engineering recommendations for flow optimization",
    ],
    keyBenefits: [
      "Improve reliable and consistent material discharge",
      "Reduce arching, bridging, and ratholing",
      "Minimize stagnant material and material build-up",
      "Reduce particle segregation during storage and discharge",
      "Improve feed uniformity to downstream equipment",
      "Increase effective storage and discharge capacity",
      "Reduce process interruptions and manual intervention",
      "Support hopper, bin, and silo design modifications",
      "Improve overall material handling reliability and plant availability",
    ],
  },
  {
    id: "05",
    slug: "dust-extraction-and-suppression-analysis",
    title: "Dust Extraction & Suppression Analysis",
    badge: "DUST EXTRACTION",
    image: "/images/cfd-engineering/bulk-material-handling/service_05.jpg",
    shortDescription:
      "Airflow entrainment and particle dispersion modeling to design hood geometry, enclosure seals, and extraction pick-up points across handling systems.",
    description: [
      "Bulk material handling operations can generate significant airborne dust during conveying, transfer, loading, unloading, storage, and discharge. Air entrainment caused by falling material, conveyor movement, and displaced air from bins or silos can spread fine particles beyond the handling equipment, resulting in material loss, equipment contamination, poor working conditions, and increased environmental emissions.",
      "MACPROTEC applies advanced CFD and particle-flow simulations to analyze dust generation, airborne particle transport, dispersion, and capture throughout bulk material handling systems. Our studies evaluate extraction airflow, hood configuration, enclosure performance, and suppression strategies to control dust at its source while minimizing unnecessary extraction airflow and energy consumption.",
    ],
    applications: [
      "Conveyor Transfer Points",
      "Chutes & Hoppers",
      "Crushers & Screens",
      "Silo Loading & Discharge",
      "Truck & Wagon Loading",
      "Ship Loading & Unloading",
      "Stockpile Handling",
      "Dust Extraction Systems",
    ],
    keyAnalyses: [
      "Dust generation and particle dispersion analysis",
      "Air entrainment and induced airflow assessment",
      "Airborne particle trajectory and concentration analysis",
      "Extraction airflow and capture efficiency evaluation",
      "Hood and enclosure performance assessment",
      "Fugitive dust escape path identification",
      "Particle settling and deposition analysis",
      "Influence of cross-drafts and ambient airflow",
      "Dust suppression and extraction strategy evaluation",
      "Extraction duct and pickup-point optimization",
      "Comparative assessment of different operating conditions",
    ],
    deliverables: [
      "Dust concentration and dispersion contour maps",
      "Particle trajectory and airflow visualizations",
      "Dust capture and extraction efficiency assessment",
      "Fugitive dust escape-zone identification",
      "Hood and enclosure performance evaluation",
      "Airflow requirement and extraction performance assessment",
      "Comparative evaluation of dust-control alternatives",
      "Engineering recommendations for system optimization",
    ],
    keyBenefits: [
      "Reduce fugitive dust emissions",
      "Improve dust capture at material transfer points",
      "Reduce material losses and equipment contamination",
      "Improve workplace air quality and visibility",
      "Optimize extraction airflow and fan energy consumption",
      "Reduce dust accumulation and housekeeping requirements",
      "Improve performance of existing dust-control systems",
      "Support effective enclosure and extraction-system design",
      "Improve environmental performance and overall handling-system reliability",
    ],
  },
  {
    id: "06",
    slug: "conveyor-transfer-and-loading-analysis",
    title: "Conveyor Transfer & Loading Analysis",
    badge: "CONVEYOR LOADING",
    image: "/images/cfd-engineering/bulk-material-handling/service_06.jpg",
    shortDescription:
      "Simulation of conveyor belt material landing points, belt speed matching, material centering, off-center loading mitigation, and rollback prevention.",
    description: [
      "Conveyor systems are central to continuous bulk material transport, and their performance depends heavily on how material is transferred, loaded, accelerated, and distributed onto the belt. Poor loading conditions can cause off-center loading, spillage, material rollback, excessive impact, belt wear, dust generation, and unstable downstream conveying.",
      "MACPROTEC applies advanced CFD-DEM and particle-flow simulations to analyze material behavior at conveyor loading and transfer zones. Our studies evaluate particle trajectories, material velocity, impact behavior, belt loading patterns, and air-particle interaction to optimize transfer geometry and achieve controlled, centered, and efficient material loading.",
    ],
    applications: [
      "Belt Conveyor Loading",
      "Conveyor-to-Conveyor Transfers",
      "Feed & Discharge Zones",
      "Loading Chutes",
      "Belt Feeders",
      "Tripper Conveyors",
      "Ship & Wagon Loading",
      "Stockyard Conveying Systems",
    ],
    keyAnalyses: [
      "Material trajectory and landing-point analysis",
      "Belt loading and material distribution assessment",
      "Material velocity matching with conveyor belt speed",
      "Off-center loading and belt mistracking risk assessment",
      "Particle impact velocity and impact-energy analysis",
      "Spillage and material rollback investigation",
      "Material acceleration and deceleration analysis",
      "Particle segregation and distribution assessment",
      "Air entrainment and dust-generation potential",
      "Transfer capacity and throughput evaluation",
      "Loading chute geometry optimization",
    ],
    deliverables: [
      "Particle trajectory and conveyor loading visualizations",
      "Belt material distribution and loading profiles",
      "Material landing-point and velocity assessment",
      "Impact and high-wear zone identification",
      "Spillage and off-center loading assessment",
      "Dust-generation and air-entrainment evaluation",
      "Comparative assessment of loading configurations",
      "Engineering recommendations for conveyor optimization",
    ],
    keyBenefits: [
      "Achieve centered and uniform conveyor loading",
      "Reduce material spillage and rollback",
      "Minimize belt, chute, and liner wear",
      "Reduce impact loads at conveyor transfer zones",
      "Improve belt tracking and conveyor reliability",
      "Reduce dust generation during material transfer",
      "Increase conveying capacity and flow stability",
      "Reduce maintenance requirements and belt damage",
      "Improve overall material handling efficiency and availability",
    ],
  },
  {
    id: "07",
    slug: "erosion-and-wear-analysis",
    title: "Erosion & Wear Analysis",
    badge: "EROSION & WEAR",
    image: "/images/cfd-engineering/bulk-material-handling/service_07.jpg",
    shortDescription:
      "Quantitative prediction of particle impact angles, sliding friction wear, liner wear-rate maps (mm/year), and protective liner arrangement optimization.",
    description: [
      "Bulk material handling systems are continuously exposed to abrasive particles moving at high velocities and impacting equipment surfaces. Repeated particle impact and sliding can cause severe localized wear in chutes, bends, conveying lines, diverters, and loading equipment, leading to material loss, equipment damage, increased maintenance, and unexpected shutdowns.",
      "MACPROTEC applies advanced CFD, particle tracking, and CFD-DEM simulations to predict particle trajectories, impact velocity, impact angle, wall interaction, and erosion-prone regions throughout bulk material handling systems. Our analyses identify the mechanisms responsible for excessive wear and help optimize equipment geometry, operating conditions, and wear-protection arrangements to extend equipment service life.",
    ],
    applications: [
      "Transfer Chutes",
      "Pneumatic Conveying Lines",
      "Pipe Bends & Elbows",
      "Diverters & Splitters",
      "Hoppers & Feeders",
      "Loading Systems",
      "Cyclones & Separators",
      "Material Transfer Equipment",
    ],
    keyAnalyses: [
      "Particle trajectory and wall-impact analysis",
      "Erosion rate and wear-pattern prediction",
      "Particle impact velocity and impact angle assessment",
      "Sliding and abrasive wear-zone identification",
      "High-velocity and high-impact region analysis",
      "Particle concentration and solids loading assessment",
      "Wear analysis at bends, transitions, and flow restrictions",
      "Influence of particle size, shape, and material properties",
      "Liner configuration and wear-protection assessment",
      "Geometry modification and wear-reduction studies",
      "Comparative evaluation of operating conditions",
    ],
    deliverables: [
      "Erosion and wear-rate contour maps",
      "Particle trajectory and impact visualizations",
      "Critical wear-location identification",
      "Impact velocity and angle distribution assessment",
      "Relative wear comparison between design alternatives",
      "Liner and wear-protection performance assessment",
      "Comparative evaluation of geometry modifications",
      "Engineering recommendations for wear mitigation",
    ],
    keyBenefits: [
      "Identify high-wear regions before equipment failure",
      "Reduce localized erosion and material loss",
      "Extend chute, pipeline, and equipment service life",
      "Optimize liner placement and wear protection",
      "Reduce maintenance frequency and replacement costs",
      "Minimize unexpected failures and production interruptions",
      "Improve equipment geometry to reduce particle impact",
      "Validate wear-reduction modifications before implementation",
      "Improve overall material handling reliability and availability",
    ],
  },
  {
    id: "08",
    slug: "root-cause-cfd-investigation",
    title: "Root Cause CFD Investigation",
    badge: "FAILURE DIAGNOSTICS",
    image: "/images/cfd-engineering/bulk-material-handling/service_08.jpg",
    shortDescription:
      "Multi-physics CFD and CFD-DEM investigation to isolate physical mechanisms causing recurring chute blockages, dust escape, and material hang-up.",
    description: [
      "Recurring problems in bulk material handling systems are often caused by complex interactions between airflow, particle behavior, equipment geometry, material properties, and operating conditions. Issues such as repeated blockages, excessive dust, abnormal wear, material build-up, uneven distribution, spillage, and inadequate conveying capacity can be difficult to diagnose through plant observations and conventional calculations alone.",
      "MACPROTEC applies advanced CFD, particle tracking, and CFD-DEM simulations to recreate actual operating conditions and identify the physical mechanisms responsible for these problems. By combining simulation results with plant operating data, we isolate the root cause, quantify its impact, and evaluate practical corrective modifications before implementation.",
    ],
    applications: [
      "Transfer Chutes & Transfer Points",
      "Pneumatic Conveying Systems",
      "Conveyors & Loading Systems",
      "Hoppers, Bins & Silos",
      "Dust Extraction Systems",
      "Diverters & Distribution Systems",
      "Cyclones & Separators",
      "Bulk Material Handling Equipment",
    ],
    keyAnalyses: [
      "Material blockage and build-up investigation",
      "Abnormal particle trajectory and flow restriction analysis",
      "Uneven material distribution and segregation assessment",
      "Dust generation, dispersion, and escape investigation",
      "Excessive erosion and localized wear analysis",
      "Pneumatic conveying pressure loss and deposition assessment",
      "Air entrainment and unwanted airflow investigation",
      "Spillage and uncontrolled discharge analysis",
      "Equipment capacity and throughput limitation assessment",
      "Comparison of actual versus intended operating conditions",
      "Evaluation of corrective geometry and operating modifications",
    ],
    deliverables: [
      "Root cause CFD / CFD-DEM investigation report",
      "Particle trajectory, airflow, and material distribution visualizations",
      "Identification of performance-limiting mechanisms",
      "Blockage, build-up, dust, or wear-zone assessment",
      "Quantification of relevant flow and particle behavior",
      "Comparative assessment of corrective alternatives",
      "Engineering recommendations and remedial actions",
      "Technical guidance for implementation",
    ],
    keyBenefits: [
      "Identify the actual cause of recurring handling problems",
      "Reduce repeated troubleshooting and ineffective modifications",
      "Eliminate blockages, build-up, and flow restrictions",
      "Reduce excessive dust, spillage, and material losses",
      "Minimize erosion and premature equipment wear",
      "Improve conveying capacity and material distribution",
      "Reduce unplanned downtime and maintenance costs",
      "Validate corrective solutions before implementation",
      "Improve long-term material handling reliability and plant availability",
    ],
  },
];
