export interface CementService {
  id: string;
  slug: string;
  title: string;
  badge: string;
  image: string;
  shortDescription: string;
  description: string[];
  applications: string[];
  keyAnalyses: string[];
  deliverables: string[];
  keyBenefits: string[];
}

export const CEMENT_SERVICES: CementService[] = [
  {
    id: "01",
    slug: "flow-and-pressure-analysis",
    title: "Flow & Pressure CFD Analysis",
    badge: "FLUID DYNAMICS",
    image: "/images/cement/service-flow-pressure.jpg",
    shortDescription:
      "Gas and fluid flow modeling within kilns, cyclones, mills, ducting, and fans to minimize pressure losses and balance draft systems.",
    description: [
      "Flow and pressure behavior are critical to the performance of cement manufacturing processes. Uneven airflow, excessive pressure losses, recirculation zones, and flow restrictions can reduce equipment efficiency, increase energy consumption, and limit production capacity. Using advanced Computational Fluid Dynamics (CFD), MACPROTEC analyzes complex gas and fluid flow within cement plant process systems to identify performance limitations and develop practical engineering solutions.",
      "Our CFD studies provide a detailed understanding of flow patterns, pressure distribution, velocity profiles, and system hydraulics, enabling optimized equipment operation, improved process stability, and reduced operating costs.",
    ],
    applications: [
      "Rotary Kilns",
      "Cyclones & Preheater Towers",
      "Raw Mills & Cement Mills",
      "Fan & Duct Systems",
      "Clinker Coolers",
      "Bag Filters",
      "Gas Conditioning Towers",
      "Waste Heat Recovery Systems",
    ],
    keyAnalyses: [
      "Flow Distribution Analysis",
      "Pressure Drop Evaluation",
      "Velocity Profile Analysis",
      "Flow Uniformity Assessment",
      "Flow Restriction Identification",
      "Recirculation Zone Analysis",
      "False Air Investigation",
      "Draft System Evaluation",
      "Fan Performance Assessment",
      "Flow Balancing Studies",
    ],
    deliverables: [
      "CFD Engineering Report",
      "Pressure & Velocity Contour Plots",
      "Flow Streamline Visualization",
      "Pressure Loss Assessment",
      "Performance Evaluation",
      "Engineering Recommendations",
      "Design Modification Proposals",
    ],
    keyBenefits: [
      "Reduce pressure losses across process systems",
      "Improve gas flow distribution and process stability",
      "Increase equipment efficiency and production capacity",
      "Reduce fan power consumption",
      "Eliminate flow restrictions and dead zones",
      "Improve overall plant reliability",
      "Support data-driven engineering decisions",
    ],
  },
  {
    id: "02",
    slug: "thermal-and-heat-transfer-analysis",
    title: "Thermal & Heat Transfer CFD Analysis",
    badge: "THERMAL & ENERGY",
    image: "/images/cement/service-thermal-heat-transfer.jpg",
    shortDescription:
      "Convective, conductive, and radiative heat transfer evaluation to improve thermal efficiency, lower fuel use, and stop hot spots.",
    description: [
      "Thermal performance is one of the most critical factors influencing production capacity, fuel efficiency, equipment reliability, and product quality in cement manufacturing. Uneven temperature distribution, excessive heat losses, inefficient heat recovery, and localized hot or cold zones can significantly impact process stability and operational costs. Using advanced Computational Fluid Dynamics (CFD), MACPROTEC evaluates heat transfer mechanisms, thermal behavior, and temperature distribution within cement process systems to identify opportunities for performance improvement.",
      "Our engineering analyses provide valuable insights into convective, conductive, and radiative heat transfer, enabling optimized thermal efficiency, improved energy utilization, and enhanced equipment performance across the cement production process.",
    ],
    applications: [
      "Rotary Kilns",
      "Calciners",
      "Clinker Coolers",
      "Waste Heat Recovery Systems",
      "Gas Conditioning Towers",
      "Raw Mills",
      "Cement Mills",
      "Hot Gas Duct Systems",
    ],
    keyAnalyses: [
      "Temperature Distribution Analysis",
      "Heat Transfer Evaluation",
      "Heat Loss Assessment",
      "Thermal Efficiency Analysis",
      "Hot & Cold Spot Identification",
      "Heat Recovery Assessment",
      "Gas Temperature Distribution",
      "Thermal Performance Evaluation",
      "Process Heat Balance Verification",
      "Thermal Optimization Studies",
    ],
    deliverables: [
      "CFD Engineering Report",
      "Temperature Contour Plots",
      "Heat Flux Visualization",
      "Thermal Performance Assessment",
      "Heat Loss Engineering Recommendations",
      "Thermal Optimization Proposals",
    ],
    keyBenefits: [
      "Improve thermal efficiency across the process",
      "Reduce fuel and energy consumption",
      "Enhance heat recovery performance",
      "Eliminate thermal imbalances and hot spots",
      "Improve process stability and clinker quality",
      "Increase equipment reliability and operational efficiency",
      "Support energy optimization and sustainability initiatives",
    ],
  },
  {
    id: "03",
    slug: "combustion-cfd-analysis",
    title: "Combustion CFD Analysis",
    badge: "PYROPROCESSING",
    image: "/images/cement/service-combustion-cfd.jpg",
    shortDescription:
      "Flame shape stability, fuel-air mixing, alternative fuel co-processing, and heat release optimization for kiln burners and calciners.",
    description: [
      "Efficient combustion is fundamental to achieving stable kiln operation, high clinker quality, and optimal fuel utilization in cement manufacturing. Poor fuel-air mixing, unstable flame characteristics, uneven temperature distribution, and inefficient combustion can lead to increased fuel consumption, higher emissions, refractory damage, and reduced production efficiency. Using advanced Computational Fluid Dynamics (CFD), MACPROTEC analyzes combustion processes to evaluate flame behavior, fuel-air interaction, heat release, and gas flow characteristics, enabling optimized burner performance and improved thermal efficiency.",
      "Our engineering studies support the optimization of conventional and alternative fuel combustion, helping cement plants improve operational stability, reduce emissions, and maximize overall pyroprocessing performance.",
    ],
    applications: [
      "Rotary Kiln Burners",
      "Calciners",
      "Alternative Fuel Combustion Systems",
      "Multi-Fuel Burners",
      "Pyroprocessing Systems",
      "Combustion Air Distribution Systems",
    ],
    keyAnalyses: [
      "Flame Shape & Stability Analysis",
      "Fuel-Air Mixing Assessment",
      "Temperature Distribution Analysis",
      "Combustion Efficiency Evaluation",
      "Oxygen Distribution Analysis",
      "Residence Time Assessment",
      "Alternative Fuel Performance Evaluation",
      "Heat Release Analysis",
      "NOx Formation Assessment",
      "Combustion System Optimization",
    ],
    deliverables: [
      "CFD Engineering Report",
      "Flame & Temperature Contour Plots",
      "Combustion Performance Assessment",
      "Fuel-Air Mixing Analysis",
      "Engineering Recommendations",
      "Combustion Optimization Proposals",
    ],
    keyBenefits: [
      "Improve combustion efficiency and fuel utilization",
      "Enhance flame stability and temperature uniformity",
      "Support alternative fuel implementation",
      "Reduce fuel consumption and operating costs",
      "Minimize emissions and environmental impact",
      "Improve clinker quality and process stability",
      "Increase overall kiln and calciner performance",
    ],
  },
  {
    id: "04",
    slug: "multiphase-and-gas-solid-flow-analysis",
    title: "Multiphase & Gas-Solid Flow CFD Analysis",
    badge: "MULTIPHASE FLOW",
    image: "/images/cement/service-multiphase-gas-solid.jpg",
    shortDescription:
      "Particle transport, gas-solid interactions, separation efficiency, and wear mitigation in cyclones, separators, and mill circuits.",
    description: [
      "Many critical processes in cement manufacturing involve the interaction between gas streams and solid particles. The behavior of these gas-solid flows directly influences process efficiency, separation performance, heat transfer, material transport, and overall plant productivity. Using advanced Computational Fluid Dynamics (CFD), MACPROTEC analyzes complex multiphase flow behavior to evaluate particle transport, gas-solid interactions, flow distribution, and separation efficiency within cement process systems.",
      "Our engineering studies help identify material build-up, particle carryover, uneven gas-solid distribution, excessive wear, and operational inefficiencies, enabling optimized equipment performance, improved process reliability, and enhanced production efficiency.",
    ],
    applications: [
      "Cyclones & Preheater Systems",
      "Clinker Coolers",
      "Dynamic Separators",
      "Pneumatic Conveying Systems",
      "Raw & Cement Mills",
      "Alternative Fuel Injection Systems",
    ],
    keyAnalyses: [
      "Gas-Solid Flow Distribution",
      "Particle Trajectory Analysis",
      "Particle Separation Efficiency",
      "Material Carryover Assessment",
      "Particle Residence Time Evaluation",
      "Solids Concentration Distribution",
      "Particle Deposition & Build-up Analysis",
      "Erosion & Wear Prediction",
      "Gas-Solid Mixing Evaluation",
      "Process Performance Optimization",
    ],
    deliverables: [
      "CFD Engineering Report",
      "Particle Flow Visualization",
      "Gas-Solid Flow Contour Plots",
      "Separation Performance Assessment",
      "Material Transport Evaluation",
      "Engineering Recommendations",
      "Equipment Optimization Proposals",
    ],
    keyBenefits: [
      "Improve gas-solid flow distribution",
      "Increase separation efficiency",
      "Reduce material carryover and product losses",
      "Minimize material build-up and equipment wear",
      "Enhance process stability and operational reliability",
      "Improve material transport efficiency",
      "Optimize overall equipment performance",
    ],
  },
  {
    id: "05",
    slug: "dust-collection-and-separation-analysis",
    title: "Dust Collection & Separation CFD Analysis",
    badge: "ENVIRONMENTAL & APC",
    image: "/images/cement/service-dust-collection-separation.jpg",
    shortDescription:
      "Airflow distribution, particulate capture, and pressure drop optimization across bag filters, ESPs, and cyclones for strict compliance.",
    description: [
      "Efficient dust collection and particle separation are essential for maintaining environmental compliance, reducing product losses, and ensuring reliable operation in cement plants. Poor airflow distribution, uneven dust loading, high pressure losses, and inefficient particle separation can increase emissions, reduce equipment performance, and raise operating costs. Using advanced Computational Fluid Dynamics (CFD), MACPROTEC analyzes airflow behavior, particle transport, and separation performance to optimize dust collection systems and improve overall process efficiency.",
      "Our engineering studies provide valuable insights into gas-solid flow patterns, particle separation efficiency, dust distribution, and system hydraulics, enabling improved environmental performance, reduced maintenance requirements, and enhanced operational reliability.",
    ],
    applications: [
      "Bag Filters",
      "Electrostatic Precipitators (ESPs)",
      "Cyclones & Multi-Cyclones",
      "Dynamic Separators",
      "Dust Collection Duct Systems",
      "Process Exhaust Systems",
    ],
    keyAnalyses: [
      "Airflow Distribution Analysis",
      "Particle Separation Efficiency Assessment",
      "Dust Loading Distribution",
      "Pressure Drop Evaluation",
      "Velocity Profile Analysis",
      "Particle Carryover Analysis",
      "Dust Re-entrainment Assessment",
      "Flow Uniformity Evaluation",
      "Collection Efficiency Analysis",
      "System Performance Optimization",
    ],
    deliverables: [
      "CFD Engineering Report",
      "Airflow & Particle Flow Visualization",
      "Pressure & Velocity Contour Plots",
      "Separation Performance Assessment",
      "Dust Collection Efficiency Evaluation",
      "Engineering Recommendations",
      "System Optimization Proposals",
    ],
    keyBenefits: [
      "Improve dust collection and separation efficiency",
      "Reduce particulate emissions and product losses",
      "Minimize pressure losses across collection systems",
      "Improve airflow distribution and filter utilization",
      "Reduce maintenance requirements and operating costs",
      "Enhance environmental compliance and plant reliability",
      "Optimize overall dust collection system performance",
    ],
  },
  {
    id: "06",
    slug: "pneumatic-conveying-analysis",
    title: "Pneumatic Conveying CFD Analysis",
    badge: "BULK HANDLING",
    image: "/images/cement/service-pneumatic-conveying.jpg",
    shortDescription:
      "Air-solid flow dynamics, pipeline wear prediction, deposition prevention, and blockage risk mitigation for fine bulk material transport.",
    description: [
      "Pneumatic conveying systems play a critical role in the reliable transport of cement, raw meal, fly ash, and other fine bulk materials throughout the cement manufacturing process. Poor conveying performance can result in excessive pressure losses, pipeline wear, material deposition, blockages, inconsistent material flow, and increased energy consumption. Using advanced Computational Fluid Dynamics (CFD), MACPROTEC analyzes air-solid flow behavior, particle transport, and conveying system performance to optimize material handling and improve operational reliability.",
      "Our engineering studies provide detailed insights into flow characteristics, pressure distribution, particle movement, and system performance, enabling efficient material transport while reducing maintenance requirements and operating costs.",
    ],
    applications: [
      "Cement Conveying Systems",
      "Raw Meal Conveying Systems",
      "Fly Ash Conveying Systems",
      "Alternative Fuel Conveying Systems",
      "Kiln Dust Conveying Systems",
      "Dense & Dilute Phase Conveying Systems",
    ],
    keyAnalyses: [
      "Air-Solid Flow Analysis",
      "Particle Transport Evaluation",
      "Pressure Drop Assessment",
      "Pipeline Velocity Analysis",
      "Material Distribution Assessment",
      "Particle Deposition & Build-up Analysis",
      "Pipeline Wear Prediction",
      "Blockage Risk Assessment",
      "Conveying Efficiency Evaluation",
      "System Performance Optimization",
    ],
    deliverables: [
      "CFD Engineering Report",
      "Airflow & Particle Flow Visualization",
      "Pressure & Velocity Contour Plots",
      "Conveying Performance Assessment",
      "Pipeline Wear & Deposition Evaluation",
      "Engineering Recommendations",
      "Conveying System Optimization Proposals",
    ],
    keyBenefits: [
      "Improve conveying efficiency and system reliability",
      "Reduce pressure losses and energy consumption",
      "Minimize pipeline wear and maintenance costs",
      "Prevent material build-up and blockages",
      "Improve material distribution and transport stability",
      "Extend conveying system service life",
      "Optimize overall bulk material handling performance",
    ],
  },
  {
    id: "07",
    slug: "pipe-stress-analysis-and-support-design",
    title: "Pipe Stress Analysis & Support Design",
    badge: "PIPING INTEGRITY",
    image: "/images/cement/service-pipe-stress.jpg",
    shortDescription:
      "Thermal expansion, sustained/occasional loading, equipment nozzle protection, and support optimization for hot gas and utility lines.",
    description: [
      "Piping systems in cement plants are subjected to high temperatures, thermal expansion, dead loads, pressure fluctuations, and dynamic operating conditions. Inadequate piping flexibility or improperly designed support systems can lead to excessive stresses, equipment nozzle overloads, structural failures, vibration issues, and unplanned shutdowns. MACPROTEC performs comprehensive pipe stress analyses to evaluate piping integrity, ensure compliance with international design standards, and optimize support configurations for safe and reliable operation.",
      "Our engineering studies assess the mechanical behavior of process piping under various operating and transient conditions, enabling optimized support layouts, improved equipment protection, and enhanced long-term plant reliability.",
    ],
    applications: [
      "Kiln Hot Gas Duct Systems",
      "Raw Mill Gas Ducts",
      "Cement Mill Gas Ducts",
      "Alternative Fuel Piping",
      "Compressed Air Systems",
      "Cooling Water Pipelines",
      "Steam & Condensate Systems",
      "Process Utility Piping",
    ],
    keyAnalyses: [
      "Static Pipe Stress Analysis",
      "Thermal Expansion Analysis",
      "Pipe Flexibility Assessment",
      "Equipment Nozzle Load Evaluation",
      "Pipe Support Design & Optimization",
      "Sustained & Occasional Load Analysis",
      "Hanger & Support Selection",
      "Structural Interaction Assessment",
      "Vibration Assessment",
      "Code Compliance Verification",
    ],
    deliverables: [
      "Pipe Stress Analysis Report",
      "Stress & Displacement Results",
      "Pipe Support Layout Drawings",
      "Support Design Calculations",
      "Equipment Nozzle Load Report",
      "Engineering Recommendations",
      "Piping Modification Proposals",
    ],
    keyBenefits: [
      "Ensure piping system integrity and code compliance",
      "Prevent failures caused by thermal expansion and excessive stresses",
      "Protect equipment nozzles and connected machinery",
      "Optimize pipe support arrangements and reduce structural loads",
      "Improve plant reliability and operational safety",
      "Minimize maintenance requirements and unplanned downtime",
      "Extend the service life of piping systems",
    ],
  },
  {
    id: "08",
    slug: "root-cause-cfd-investigation",
    title: "Root Cause CFD Investigation",
    badge: "TROUBLESHOOTING",
    image: "/images/cement/service-root-cause-cfd.jpg",
    shortDescription:
      "Forensic fluid dynamics to diagnose false air infiltration, pressure loss spikes, material build-up, severe wear, and plant bottlenecks.",
    description: [
      "Operational challenges in cement plants often arise from complex flow, thermal, or gas-solid interactions that cannot be fully understood through conventional plant measurements alone. Issues such as excessive pressure losses, unstable process conditions, uneven gas distribution, false air infiltration, material build-up, poor separation efficiency, and reduced production capacity frequently originate from underlying fluid flow behavior. Using advanced Computational Fluid Dynamics (CFD), MACPROTEC performs systematic root cause investigations to identify the mechanisms responsible for process inefficiencies and equipment performance limitations.",
      "Our engineering studies provide detailed insight into process behavior and develop practical, data-driven recommendations that improve plant reliability, operational efficiency, and long-term performance.",
    ],
    applications: [
      "False Air Investigation",
      "High Pressure Loss Analysis",
      "Uneven Gas Flow Distribution",
      "Material Build-up & Blockage Analysis",
      "Equipment Performance Troubleshooting",
      "Production Bottleneck Investigation",
    ],
    keyAnalyses: [
      "Flow Pattern Evaluation",
      "Pressure Distribution Analysis",
      "Velocity Profile Assessment",
      "Temperature Distribution Analysis",
      "Gas-Solid Flow Investigation",
      "Air Leakage Assessment",
      "Recirculation & Dead Zone Identification",
      "Particle Transport Analysis",
      "Equipment Performance Assessment",
      "Engineering Solution Evaluation",
    ],
    deliverables: [
      "Root Cause Investigation Report",
      "CFD Flow & Thermal Visualization",
      "Performance Assessment",
      "Problem Identification & Engineering Diagnosis",
      "Corrective Action Recommendations",
      "Design Improvement Proposals",
    ],
    keyBenefits: [
      "Identify the true cause of process and equipment issues",
      "Eliminate trial-and-error troubleshooting",
      "Improve plant reliability and process stability",
      "Reduce production losses and operational downtime",
      "Optimize equipment performance and energy efficiency",
      "Support informed engineering and maintenance decisions",
      "Enable sustainable long-term performance improvements",
    ],
  },
];
