export interface ChemicalService {
  id: string;
  slug: string;
  title: string;
  badge: string;
  image: string;
  shortDescription: string;
  description: string[];
  applications: string[];
  keyAnalyses: string[];
  deliverables: string[];
  keyBenefits: string[];
}

export const CHEMICAL_SERVICES: ChemicalService[] = [
  {
    id: "01",
    slug: "mixing-agitation-and-reactor-cfd-analysis",
    title: "Mixing, Agitation & Reactor CFD Analysis",
    badge: "REACTOR & MIXING",
    image: "/images/cfd-engineering/chemical/service_01.jpg",
    shortDescription:
      "CFD modeling of fluid circulation, impeller dynamics, reactant homogenization, residence time distribution (RTD), and dead-zone elimination in chemical reactors.",
    description: [
      "Mixing and reaction performance are critical to product quality, conversion efficiency, process stability, and energy consumption in chemical manufacturing. Poor circulation, inadequate mixing, dead zones, short-circuiting, or non-uniform reactant distribution can result in incomplete reactions, inconsistent product quality, excessive batch time, and increased operating costs.",
      "MACPROTEC applies advanced CFD simulations to analyze fluid circulation, mixing dynamics, species distribution, heat transfer, and reaction behavior inside chemical reactors and mixing equipment. Our studies help optimize agitator configuration, operating conditions, feed locations, and vessel internals to achieve uniform mixing, efficient mass transfer, and improved reactor performance.",
    ],
    applications: [
      "Stirred Tank Reactors",
      "Mixing & Blending Vessels",
      "Batch & Continuous Reactors",
      "Static Mixers",
      "Chemical Dosing Systems",
      "Gas-Liquid Reactors",
      "Polymerization Reactors",
      "Neutralization Tanks",
    ],
    keyAnalyses: [
      "Mixing and circulation pattern analysis",
      "Agitator and impeller performance evaluation",
      "Velocity distribution and dead-zone identification",
      "Mixing time and homogenization assessment",
      "Residence time distribution (RTD) analysis",
      "Species and reactant concentration distribution",
      "Gas-liquid dispersion and mass transfer analysis",
      "Temperature and heat transfer uniformity assessment",
      "Reaction and species transport modeling",
      "Impeller type, speed, position, and configuration optimization",
      "Feed/injection location optimization",
    ],
    deliverables: [
      "Velocity, streamline, and circulation visualizations",
      "Mixing time and uniformity assessment",
      "Species/concentration distribution contours",
      "Residence time distribution analysis",
      "Dead-zone and short-circuiting identification",
      "Agitator and impeller performance assessment",
      "Comparative evaluation of design and operating scenarios",
      "Engineering recommendations for mixing and reactor optimization",
    ],
    keyBenefits: [
      "Improve mixing uniformity and reaction efficiency",
      "Reduce mixing and batch processing time",
      "Eliminate dead zones and poor circulation regions",
      "Improve reactant and additive distribution",
      "Enhance product consistency and quality",
      "Improve heat and mass transfer performance",
      "Reduce agitator power consumption through optimized operation",
      "Support reactor debottlenecking and capacity improvement",
      "Validate design modifications before plant implementation",
    ],
  },
  {
    id: "02",
    slug: "multiphase-and-reactive-flow-cfd-analysis",
    title: "Multiphase & Reactive Flow CFD Analysis",
    badge: "MULTIPHASE REACTION",
    image: "/images/cfd-engineering/chemical/service_02.jpg",
    shortDescription:
      "Simulation of complex gas-liquid-solid interactions, species transport, interphase mass transfer, and chemical kinetics in multiphase chemical reactors.",
    description: [
      "Many chemical processes involve simultaneous interaction between multiple phases—gas, liquid, and solid—often combined with chemical reactions, heat transfer, and mass transfer. Complex phase behavior, poor dispersion, inadequate contact between reactants, particle settling, or non-uniform reaction zones can reduce conversion efficiency, affect product quality, and create operational limitations.",
      "MACPROTEC applies advanced multiphase and reactive CFD modeling to simulate phase interactions, species transport, chemical reactions, and mass transfer within chemical process equipment. Our analyses provide detailed insight into phase distribution, reaction behavior, residence time, and transport phenomena, supporting equipment optimization, process debottlenecking, and improved operating performance.",
    ],
    applications: [
      "Bubble Column Reactors",
      "Gas-Liquid Reactors",
      "Slurry Reactors",
      "Fluidized Bed Reactors",
      "Absorbers & Scrubbers",
      "Crystallizers",
      "Gas-Solid Contactors",
      "Multiphase Process Vessels",
    ],
    keyAnalyses: [
      "Gas-liquid, liquid-liquid, and gas-solid flow behavior",
      "Phase distribution and volume fraction analysis",
      "Bubble, droplet, and particle dispersion assessment",
      "Species transport and concentration distribution",
      "Chemical reaction and reaction-rate modeling",
      "Interphase heat and mass transfer analysis",
      "Gas-liquid contact and mass transfer efficiency",
      "Particle settling, suspension, and entrainment analysis",
      "Residence time and reaction-zone distribution",
      "Flow regime and phase interaction assessment",
      "Operating condition and equipment configuration comparison",
    ],
    deliverables: [
      "Phase distribution and volume fraction contours",
      "Velocity and multiphase flow visualizations",
      "Species concentration and reaction distribution maps",
      "Bubble, droplet, or particle trajectory analysis",
      "Heat and mass transfer performance assessment",
      "Residence time and reaction-zone evaluation",
      "Comparative analysis of operating and design scenarios",
      "Engineering recommendations for process optimization",
    ],
    keyBenefits: [
      "Improve phase contact and reaction efficiency",
      "Increase chemical conversion and process performance",
      "Improve gas-liquid and gas-solid mass transfer",
      "Reduce phase maldistribution and stagnant regions",
      "Minimize particle settling and unwanted accumulation",
      "Improve product consistency and process stability",
      "Support reactor and process equipment debottlenecking",
      "Optimize operating conditions before implementation",
      "Enhance overall equipment efficiency and production capacity",
    ],
  },
  {
    id: "03",
    slug: "thermal-and-heat-transfer-analysis",
    title: "Thermal & Heat Transfer Analysis",
    badge: "THERMAL MANAGEMENT",
    image: "/images/cfd-engineering/chemical/service_03.jpg",
    shortDescription:
      "Evaluation of thermal gradients, jacket/coil heating efficiency, heat losses, and hot spot diagnostics across reactors and chemical processing equipment.",
    description: [
      "Thermal management is fundamental to chemical processing, where temperature directly influences reaction rates, product quality, phase behavior, equipment performance, and process safety. Uneven temperature distribution, inadequate heating or cooling, localized hot spots, and excessive heat losses can lead to reduced conversion, unwanted side reactions, product degradation, and unstable operation.",
      "MACPROTEC applies advanced CFD and thermal simulations to evaluate temperature distribution, heat transfer mechanisms, thermal gradients, and heating or cooling performance within chemical process equipment. Our analyses help optimize thermal conditions, improve energy utilization, identify temperature-related limitations, and support equipment design, retrofit, and process improvement.",
    ],
    applications: [
      "Chemical Reactors",
      "Jacketed Process Vessels",
      "Heating & Cooling Coils",
      "Fired Heaters",
      "Storage Tanks",
      "Process Piping",
      "Evaporators & Condensers",
      "Thermal Processing Equipment",
    ],
    keyAnalyses: [
      "Temperature distribution and thermal mapping",
      "Convective, conductive, and radiative heat transfer analysis",
      "Heating and cooling performance evaluation",
      "Thermal gradient and hot/cold spot identification",
      "Jacket and internal coil performance assessment",
      "Transient heating and cooling analysis",
      "Heat loss and insulation performance evaluation",
      "Temperature uniformity within reactors and vessels",
      "Coupled flow and heat transfer analysis",
      "Evaluation of operating conditions and thermal design modifications",
    ],
    deliverables: [
      "Temperature and heat flux contour visualizations",
      "Thermal distribution and uniformity assessment",
      "Heating and cooling performance evaluation",
      "Hot/cold spot and thermal gradient identification",
      "Heat loss and insulation performance assessment",
      "Jacket and coil effectiveness analysis",
      "Comparative evaluation of design and operating scenarios",
      "Engineering recommendations for thermal optimization",
    ],
    keyBenefits: [
      "Improve heating and cooling efficiency",
      "Maintain uniform and controlled process temperatures",
      "Improve reaction performance and product consistency",
      "Eliminate undesirable hot and cold zones",
      "Reduce heat losses and energy consumption",
      "Prevent thermal degradation and unwanted side reactions",
      "Improve equipment reliability and process stability",
      "Support thermal debottlenecking and capacity improvement",
      "Reduce operating costs through optimized thermal performance",
    ],
  },
  {
    id: "04",
    slug: "heat-exchanger-performance-and-flow-distribution-analysis",
    title: "Heat Exchanger Performance & Flow Distribution Analysis",
    badge: "HEAT EXCHANGERS",
    image: "/images/cfd-engineering/chemical/service_04.jpg",
    shortDescription:
      "CFD analysis of shell-side and tube-side flow distribution, bypassing, pressure drop, thermal effectiveness, and fouling mitigation.",
    description: [
      "Heat exchangers are critical to temperature control, heat recovery, and energy efficiency throughout chemical processing plants. Uneven flow distribution, bypassing, excessive pressure drop, stagnant regions, and fouling-prone zones can significantly reduce heat transfer effectiveness, increase utility consumption, and limit process capacity.",
      "MACPROTEC applies advanced CFD and thermal simulations to evaluate fluid distribution, temperature profiles, pressure losses, and heat transfer performance within heat exchangers. Our analyses identify flow maldistribution and thermal limitations, optimize headers and internal configurations, and support equipment modifications that improve exchanger duty, reliability, and energy efficiency.",
    ],
    applications: [
      "Shell-and-Tube Heat Exchangers",
      "Plate Heat Exchangers",
      "Condensers & Reboilers",
      "Process Coolers & Heaters",
      "Air-Cooled Heat Exchangers",
      "Exchanger Headers & Manifolds",
      "Waste Heat Recovery Units",
      "Evaporators",
    ],
    keyAnalyses: [
      "Shell-side and tube-side flow distribution analysis",
      "Temperature distribution and thermal effectiveness evaluation",
      "Pressure drop and hydraulic resistance assessment",
      "Flow maldistribution and bypass identification",
      "Recirculation, stagnant, and low-velocity zone analysis",
      "Header, nozzle, and distributor performance evaluation",
      "Local heat transfer coefficient assessment",
      "Fouling-prone region identification",
      "Phase-change behavior for condensers and evaporators",
      "Evaluation of operating conditions and design modifications",
    ],
    deliverables: [
      "Velocity, pressure, and temperature contour visualizations",
      "Flow distribution and maldistribution assessment",
      "Heat transfer and thermal performance evaluation",
      "Pressure drop and hydraulic performance report",
      "Bypass, recirculation, and stagnant-zone identification",
      "Fouling-risk assessment",
      "Comparative evaluation of design and operating scenarios",
      "Engineering recommendations for exchanger optimization",
    ],
    keyBenefits: [
      "Improve heat transfer efficiency and exchanger duty",
      "Reduce flow maldistribution and bypassing",
      "Lower pressure losses and pumping requirements",
      "Reduce fouling tendency and maintenance frequency",
      "Improve temperature control and process stability",
      "Increase exchanger capacity and operating efficiency",
      "Improve heat recovery and reduce utility consumption",
      "Support exchanger debottlenecking and retrofit projects",
      "Extend equipment service life and improve plant reliability",
    ],
  },
  {
    id: "05",
    slug: "gas-dispersion-and-industrial-ventilation-cfd-analysis",
    title: "Gas Dispersion & Industrial Ventilation CFD Analysis",
    badge: "VENTILATION & DISPERSION",
    image: "/images/cfd-engineering/chemical/service_05.jpg",
    shortDescription:
      "Simulation of toxic, flammable, or volatile chemical vapor dispersion, airflow patterns, ventilation effectiveness, and gas detector placement.",
    description: [
      "Chemical processing facilities may handle toxic, flammable, corrosive, or volatile substances that can present significant risks when accidentally released or inadequately ventilated. Poor airflow patterns, confined spaces, equipment congestion, and unfavorable wind conditions can lead to hazardous gas accumulation, increased personnel exposure, and potential fire or explosion risks.",
      "MACPROTEC applies advanced CFD simulations to predict gas and vapor dispersion, contaminant transport, and ventilation performance under realistic operating and environmental conditions. Our analyses help identify hazardous accumulation zones, evaluate ventilation effectiveness, optimize exhaust and air-supply arrangements, and support safer plant layouts and mitigation strategies.",
    ],
    applications: [
      "Process Buildings & Enclosures",
      "Chemical Storage Areas",
      "Tank Farms",
      "Reactor & Process Areas",
      "Pump & Compressor Rooms",
      "Toxic / Flammable Gas Releases",
      "Laboratory & Production Ventilation",
      "Emergency Release Scenarios",
    ],
    keyAnalyses: [
      "Toxic and flammable gas dispersion modeling",
      "Gas concentration and accumulation assessment",
      "Natural and mechanical ventilation performance analysis",
      "Airflow distribution and air-change effectiveness",
      "Exhaust hood and extraction system performance",
      "Gas detector location and coverage assessment",
      "Wind direction and atmospheric condition evaluation",
      "Building wake and equipment congestion effects",
      "Emergency and accidental release scenario analysis",
      "Evaluation of ventilation and mitigation modifications",
    ],
    deliverables: [
      "Gas concentration and dispersion contour maps",
      "Airflow, velocity, and streamline visualizations",
      "Hazardous gas accumulation zone identification",
      "Ventilation effectiveness assessment",
      "Flammable/toxic gas cloud extent evaluation",
      "Gas detector placement assessment",
      "Comparative evaluation of release and ventilation scenarios",
      "Engineering recommendations for ventilation and risk mitigation",
    ],
    keyBenefits: [
      "Improve control of toxic and flammable gas hazards",
      "Identify potential gas accumulation zones",
      "Improve ventilation and contaminant removal effectiveness",
      "Reduce personnel exposure to hazardous substances",
      "Support safer gas detector positioning",
      "Improve plant layout and ventilation design",
      "Evaluate mitigation measures before implementation",
      "Support process safety and risk-reduction studies",
      "Enhance overall facility safety and operational reliability",
    ],
  },
  {
    id: "06",
    slug: "pipe-stress-analysis-and-support-design",
    title: "Pipe Stress Analysis & Support Design",
    badge: "PIPING INTEGRITY",
    image: "/images/cfd-engineering/chemical/service_06.jpg",
    shortDescription:
      "Pipe stress evaluation and support layout engineering under thermal expansion, pressure, nozzle loads, and corrosive fluid conditions.",
    description: [
      "Piping systems in chemical plants operate under demanding combinations of pressure, temperature, thermal expansion, equipment movement, fluid weight, and occasional loading. Inadequate flexibility or poorly designed supports can result in excessive piping stresses, high equipment nozzle loads, leakage, fatigue, vibration, and premature failure, particularly in high-temperature and cyclic chemical processes.",
      "MACPROTEC performs comprehensive pipe stress analysis and support design to evaluate piping behavior under operating, start-up, shutdown, and upset conditions. Our engineering studies help optimize piping flexibility, support arrangements, and equipment connections while verifying compliance with applicable design codes and maintaining safe, reliable plant operation.",
    ],
    applications: [
      "Chemical Process Piping",
      "Reactor & Vessel Piping",
      "High-Temperature Lines",
      "Steam & Utility Piping",
      "Pump & Compressor Piping",
      "Chemical Transfer Lines",
      "Relief & Flare Piping",
      "Corrosive Fluid Systems",
    ],
    keyAnalyses: [
      "Sustained, thermal, and occasional stress evaluation",
      "Thermal expansion and piping flexibility analysis",
      "Equipment nozzle load assessment",
      "Pump, compressor, vessel, and exchanger connection loads",
      "Support load and displacement analysis",
      "Wind and seismic load assessment",
      "Pressure relief and dynamic load evaluation, where applicable",
      "Flange and connection integrity assessment",
      "Piping routing and flexibility optimization",
      "Applicable piping code compliance assessment",
    ],
    deliverables: [
      "Pipe stress calculation report",
      "Stress and displacement results",
      "Equipment nozzle load assessment",
      "Support reaction and load summary",
      "Support type and location recommendations",
      "Spring hanger and restraint requirements, where applicable",
      "Identification of stress-critical piping locations",
      "Recommended routing and support modifications",
      "Code compliance summary",
    ],
    keyBenefits: [
      "Ensure piping integrity and code compliance",
      "Safely accommodate thermal expansion and contraction",
      "Reduce excessive stresses and equipment nozzle loads",
      "Protect reactors, pumps, vessels, and heat exchangers",
      "Minimize fatigue, leakage, and premature piping failures",
      "Optimize piping flexibility and support arrangements",
      "Reduce maintenance requirements and unplanned shutdowns",
      "Improve long-term piping reliability and plant safety",
    ],
  },
  {
    id: "07",
    slug: "pressure-vessel-storage-tank-and-structural-fea",
    title: "Pressure Vessel, Storage Tank & Structural FEA",
    badge: "STRUCTURAL FEA",
    image: "/images/cfd-engineering/chemical/service_07.jpg",
    shortDescription:
      "Finite Element Analysis (FEA) of stress concentrations, thermal-mechanical fatigue, buckling, and nozzle loads in chemical reactors and storage tanks.",
    description: [
      "Pressure vessels, storage tanks, reactors, and supporting structures in chemical plants are exposed to complex combinations of internal or external pressure, temperature, fluid weight, nozzle loads, wind, seismic forces, and cyclic operating conditions. These loads can produce localized stress concentrations, excessive deformation, buckling, or fatigue that may compromise equipment integrity and service life.",
      "MACPROTEC applies advanced Finite Element Analysis (FEA) to evaluate the structural and thermal-mechanical behavior of critical chemical process equipment under realistic design and operating conditions. Our analyses support new equipment design, modifications, reinforcement, integrity assessment, and troubleshooting while verifying performance against applicable engineering codes and design criteria.",
    ],
    applications: [
      "Pressure Vessels",
      "Chemical Storage Tanks",
      "Reactors & Process Columns",
      "Drums & Separators",
      "Equipment Nozzles",
      "Equipment Skids",
      "Support Structures",
      "Platforms & Structural Frames",
    ],
    keyAnalyses: [
      "Static structural stress and deformation analysis",
      "Internal and external pressure assessment",
      "Thermal stress and coupled thermal-structural analysis",
      "Local stress concentration evaluation",
      "Nozzle and opening reinforcement assessment",
      "Buckling and structural stability analysis",
      "Wind and seismic load evaluation",
      "Fatigue and cyclic loading assessment",
      "Saddle, skirt, support, and anchorage analysis",
      "Evaluation of equipment modifications and reinforcement options",
    ],
    deliverables: [
      "Stress, strain, and deformation contour plots",
      "Structural and thermal FEA results",
      "Critical stress and deformation zone identification",
      "Nozzle and connection assessment",
      "Buckling and stability evaluation",
      "Fatigue assessment, where applicable",
      "Reinforcement and design modification recommendations",
      "Engineering calculation and FEA report",
    ],
    keyBenefits: [
      "Verify equipment structural integrity and design adequacy",
      "Identify critical stress and deformation before failure",
      "Reduce risk of buckling, fatigue, and structural damage",
      "Improve nozzle, support, and connection reliability",
      "Support safe equipment modification and retrofit projects",
      "Optimize reinforcement and structural configurations",
      "Extend equipment and structure service life",
      "Reduce unplanned failures and maintenance requirements",
      "Improve overall plant safety and equipment reliability",
    ],
  },
  {
    id: "08",
    slug: "root-cause-engineering-investigation",
    title: "Root Cause Engineering Investigation",
    badge: "FAILURE DIAGNOSTICS",
    image: "/images/cfd-engineering/chemical/service_08.jpg",
    shortDescription:
      "Systematic multi-physics investigation (CFD + FEA + process simulation) to pinpoint root causes of poor mixing, erosion, hot spots, or unexpected breakdowns.",
    description: [
      "Recurring operational and equipment problems in chemical plants often result from complex interactions between fluid flow, heat transfer, chemical reactions, mechanical stresses, and equipment geometry. Issues such as poor mixing, unexpected pressure losses, inadequate heat transfer, abnormal temperature distribution, vibration, erosion, or repeated equipment failures can be difficult to diagnose using plant measurements and conventional calculations alone.",
      "MACPROTEC combines CFD, FEA, process simulation, and engineering analysis to recreate actual operating conditions and systematically investigate these problems. Our approach identifies the underlying physical mechanisms responsible for performance limitations or failures and evaluates practical corrective measures before modifications are implemented in the plant.",
    ],
    applications: [
      "Reactors & Mixing Systems",
      "Process Piping",
      "Heat Exchangers",
      "Pressure Vessels",
      "Pumps & Compressors",
      "Storage Tanks",
      "Gas & Ventilation Systems",
      "Process Equipment",
    ],
    keyAnalyses: [
      "Flow restriction and abnormal pressure loss investigation",
      "Poor mixing and flow maldistribution assessment",
      "Temperature imbalance and hot/cold spot analysis",
      "Inadequate heat transfer and thermal performance investigation",
      "Multiphase flow and phase distribution assessment",
      "Erosion, corrosion-prone flow, and high-velocity zone identification",
      "Piping stress and equipment load assessment",
      "Flow-induced vibration and instability investigation",
      "Equipment capacity and performance limitation assessment",
      "Comparison of actual versus design operating conditions",
      "Evaluation of corrective modifications and operating scenarios",
    ],
    deliverables: [
      "Root cause engineering investigation report",
      "CFD, FEA, and/or process simulation results",
      "Identification of primary failure or performance mechanisms",
      "Flow, pressure, temperature, stress, and other relevant visualizations",
      "Quantification of performance-limiting factors",
      "Comparative assessment of corrective alternatives",
      "Engineering recommendations and remedial actions",
      "Technical guidance for implementation",
    ],
    keyBenefits: [
      "Identify the actual cause of recurring process and equipment problems",
      "Avoid repeated treatment of symptoms rather than underlying causes",
      "Reduce unplanned shutdowns and production losses",
      "Improve process stability and equipment reliability",
      "Prevent recurring equipment and piping failures",
      "Reduce troubleshooting, maintenance, and modification costs",
      "Validate corrective solutions before plant implementation",
      "Support evidence-based engineering decisions",
      "Improve long-term plant safety, efficiency, and reliability",
    ],
  },
];
