export interface MiningService {
  id: string;
  slug: string;
  title: string;
  badge: string;
  image: string;
  shortDescription: string;
  description: string[];
  applications: string[];
  keyAnalyses: string[];
  deliverables: string[];
  keyBenefits: string[];
}

export const MINING_SERVICES: MiningService[] = [
  {
    id: "01",
    slug: "slurry-and-multiphase-flow-analysis",
    title: "Slurry & Multiphase Flow Analysis",
    badge: "SLURRY TRANSPORT",
    image: "/images/cfd-engineering/mining/service_01.jpg",
    shortDescription:
      "Advanced CFD and multiphase flow simulation to evaluate liquid-solid behavior, particle settling, pressure drop, and slurry stability across mining pipelines.",
    description: [
      "Slurry transport is fundamental to mining and mineral processing, where water carries ore particles, concentrates, tailings, and other solids through pipelines and processing equipment. Variations in particle size, solids concentration, slurry velocity, and fluid properties can cause settling, flow instability, excessive pressure losses, erosion, and pipeline blockage, reducing system capacity and reliability.",
      "MACPROTEC applies advanced CFD and multiphase flow modeling to simulate liquid-solid behavior under realistic mining operating conditions. Our analyses evaluate solids distribution, particle settling, pressure loss, velocity profiles, and phase interaction to optimize slurry transport systems, improve hydraulic performance, and reduce operational and maintenance problems.",
    ],
    applications: [
      "Slurry Pipelines",
      "Tailings Transport Systems",
      "Hydrotransport Systems",
      "Pumping Stations",
      "Pipeline Manifolds & Headers",
      "Mineral Concentrate Transport",
      "Process Slurry Lines",
      "Slurry Distribution Systems",
    ],
    keyAnalyses: [
      "Liquid-solid multiphase flow behavior",
      "Slurry velocity and solids concentration distribution",
      "Particle settling and deposition assessment",
      "Critical transport velocity evaluation",
      "Pressure drop and hydraulic performance analysis",
      "Particle size and solids loading effects",
      "Flow regime and slurry stability assessment",
      "Pipeline erosion and high-velocity zone identification",
      "Flow distribution through branches and manifolds",
      "Operating condition and pipeline configuration comparison",
    ],
    deliverables: [
      "Slurry velocity and solids concentration contours",
      "Particle and phase distribution visualizations",
      "Pressure profile and pressure drop assessment",
      "Settling and deposition risk identification",
      "Critical transport velocity assessment",
      "Erosion-prone region identification",
      "Comparative evaluation of operating scenarios",
      "Engineering recommendations for slurry system optimization",
    ],
    keyBenefits: [
      "Improve slurry transport efficiency and reliability",
      "Minimize particle settling and pipeline deposition",
      "Reduce blockage and unplanned shutdown risks",
      "Reduce excessive pressure losses and pumping energy",
      "Optimize slurry velocity and solids concentration",
      "Minimize erosion and premature pipeline wear",
      "Improve pipeline capacity and operating flexibility",
      "Support slurry system debottlenecking and expansion",
      "Reduce maintenance costs and improve overall mining operations",
    ],
  },
  {
    id: "02",
    slug: "bulk-material-and-particle-flow-analysis",
    title: "Bulk Material & Particle Flow Analysis",
    badge: "BULK SOLIDS & DEM",
    image: "/images/cfd-engineering/mining/service_02.jpg",
    shortDescription:
      "CFD-DEM particle flow simulation to analyze ore trajectory, impact behavior, chute blockages, spillage, and material transfer point capacity.",
    description: [
      "Mining and mineral processing operations involve the continuous movement of large quantities of ore, crushed rock, mineral fines, and other particulate materials. Poor particle distribution, uncontrolled trajectories, excessive impact velocities, material build-up, and uneven flow can cause blockages, accelerated equipment wear, dust generation, material losses, and reduced plant throughput.",
      "MACPROTEC applies advanced CFD and particle-flow modeling, including CFD-DEM where appropriate, to evaluate the interaction between particles, air, and process equipment. Our analyses provide detailed insight into particle trajectories, material distribution, impact behavior, and gas-solid interactions, helping optimize material transfer systems and improve the reliability and capacity of mining operations.",
    ],
    applications: [
      "Transfer Chutes",
      "Hoppers & Bins",
      "Conveyor Transfer Points",
      "Feeders",
      "Ore Transfer Systems",
      "Crushers & Screen Feed Systems",
      "Stockpile Transfer Systems",
      "Mineral Handling Equipment",
    ],
    keyAnalyses: [
      "Particle trajectory and material flow analysis",
      "Particle velocity and distribution assessment",
      "Gas-solid interaction and entrained airflow analysis",
      "Material impact and collision behavior",
      "Dead zone and material accumulation identification",
      "Chute and transfer-point flow performance",
      "Particle segregation and size distribution behavior",
      "High-impact and wear-prone region identification",
      "Material discharge and flow uniformity assessment",
      "Evaluation of equipment geometry and operating scenarios",
    ],
    deliverables: [
      "Particle trajectory and material flow visualizations",
      "Particle velocity and concentration distribution maps",
      "Material accumulation and dead-zone assessment",
      "Impact and high-wear region identification",
      "Flow distribution and discharge performance assessment",
      "Comparative evaluation of equipment configurations",
      "CFD/CFD-DEM simulation results",
      "Engineering recommendations for material-flow optimization",
    ],
    keyBenefits: [
      "Improve bulk material flow and transfer efficiency",
      "Reduce chute blockage and material build-up",
      "Minimize particle impact and equipment wear",
      "Improve material distribution to downstream equipment",
      "Reduce material spillage and dust generation",
      "Increase handling capacity and process reliability",
      "Support chute and transfer-point design optimization",
      "Reduce maintenance requirements and unplanned downtime",
      "Improve overall material handling performance",
    ],
  },
  {
    id: "03",
    slug: "hydrocyclone-and-classification-analysis",
    title: "Hydrocyclone & Classification Analysis",
    badge: "HYDROCYCLONES",
    image: "/images/cfd-engineering/mining/service_03.jpg",
    shortDescription:
      "Simulation of swirling vortex dynamics, particle size cut-off, overflow/underflow separation efficiency, and wear reduction in classification hydrocyclones.",
    description: [
      "Hydrocyclones are widely used in mining and mineral processing for particle classification, dewatering, desliming, and solid-liquid separation. Their performance is strongly influenced by slurry properties, particle size distribution, feed pressure, internal flow patterns, and cyclone geometry. Poor operating conditions can result in inefficient classification, excessive bypass, misplaced particles, unstable vortex formation, and accelerated wear.",
      "MACPROTEC applies advanced CFD and multiphase flow modeling to analyze slurry and particle behavior inside hydrocyclones and classification systems. Our simulations provide detailed insight into the internal vortex structure, pressure distribution, particle trajectories, and separation mechanisms, enabling optimization of cyclone geometry and operating conditions for improved classification efficiency and process performance.",
    ],
    applications: [
      "Grinding Classification Circuits",
      "Hydrocyclone Clusters",
      "Desliming Circuits",
      "Dewatering Systems",
      "Tailings Classification",
      "Mineral Concentration Circuits",
      "Slurry Separation Systems",
      "Fine Particle Classification",
    ],
    keyAnalyses: [
      "Internal vortex and swirling flow analysis",
      "Slurry velocity and pressure distribution",
      "Particle trajectory and separation behavior",
      "Particle size classification performance",
      "Overflow and underflow distribution assessment",
      "Separation efficiency and cut-size evaluation",
      "Short-circuiting and particle bypass analysis",
      "Air-core formation and stability assessment",
      "Feed pressure and solids concentration effects",
      "Cyclone geometry and operating condition optimization",
    ],
    deliverables: [
      "Velocity, pressure, and vortex contour visualizations",
      "Particle trajectory and solids distribution maps",
      "Overflow and underflow performance assessment",
      "Classification and separation efficiency evaluation",
      "Cut-size and particle recovery assessment",
      "Bypass and short-circuiting identification",
      "Comparative evaluation of cyclone configurations",
      "Engineering recommendations for performance optimization",
    ],
    keyBenefits: [
      "Improve particle classification and separation efficiency",
      "Achieve more consistent overflow and underflow product quality",
      "Reduce misplaced coarse and fine particles",
      "Improve grinding circuit performance and stability",
      "Optimize cyclone capacity and operating conditions",
      "Reduce excessive pressure losses and energy consumption",
      "Minimize erosion and premature cyclone wear",
      "Support hydrocyclone debottlenecking and capacity improvement",
      "Improve overall mineral processing efficiency",
    ],
  },
  {
    id: "04",
    slug: "dust-extraction-and-suppression-analysis",
    title: "Dust Extraction & Suppression Analysis",
    badge: "DUST CONTROL",
    image: "/images/cfd-engineering/mining/service_04.jpg",
    shortDescription:
      "Airflow and particle tracking CFD analysis to optimize dust extraction hoods, capture efficiency, and suppression systems in crushing and screening plants.",
    description: [
      "Mining and mineral processing operations generate significant airborne dust during crushing, screening, conveying, loading, and material transfer. Poor dust capture, uncontrolled air movement, and ineffective suppression can lead to high particulate concentrations, material losses, equipment contamination, reduced visibility, and environmental and occupational exposure concerns.",
      "MACPROTEC applies advanced CFD and particle-flow modeling to simulate dust generation, dispersion, transport, and capture within mining facilities. Our analyses evaluate extraction airflow, hood performance, particle trajectories, and suppression effectiveness to optimize dust-control systems and minimize fugitive dust emissions.",
    ],
    applications: [
      "Crushing Stations",
      "Screening Plants",
      "Conveyor Transfer Points",
      "Chutes & Hoppers",
      "Stockpile Handling Areas",
      "Loading & Unloading Stations",
      "Ore Processing Buildings",
      "Dust Extraction Systems",
    ],
    keyAnalyses: [
      "Dust generation and particle dispersion analysis",
      "Airborne particle trajectory and concentration assessment",
      "Dust extraction and capture efficiency evaluation",
      "Extraction hood airflow and geometry optimization",
      "Local exhaust ventilation performance analysis",
      "Dust escape and fugitive emission identification",
      "Particle settling and deposition assessment",
      "Influence of cross-drafts and surrounding airflow",
      "Dust suppression effectiveness assessment",
      "Extraction airflow requirement and operating scenario evaluation",
    ],
    deliverables: [
      "Dust concentration and dispersion contour maps",
      "Particle trajectory and airflow visualizations",
      "Dust capture and extraction efficiency assessment",
      "Fugitive dust escape zone identification",
      "Hood and extraction system performance evaluation",
      "Particle deposition and accumulation maps",
      "Comparative assessment of extraction and suppression scenarios",
      "Engineering recommendations for dust-control optimization",
    ],
    keyBenefits: [
      "Improve dust capture and suppression effectiveness",
      "Reduce fugitive dust emissions",
      "Improve air quality around processing and transfer areas",
      "Reduce worker exposure to airborne particulates",
      "Minimize material losses and equipment contamination",
      "Optimize extraction airflow and energy consumption",
      "Improve performance of existing dust-control systems",
      "Support safer and cleaner mining operations",
      "Reduce maintenance and housekeeping requirements",
    ],
  },
  {
    id: "05",
    slug: "mine-ventilation-and-airflow-cfd-analysis",
    title: "Mine Ventilation & Airflow CFD Analysis",
    badge: "MINE VENTILATION",
    image: "/images/cfd-engineering/mining/service_05.jpg",
    shortDescription:
      "3D CFD simulation of underground mine ventilation airways, fan balancing, heat transport, diesel particulate matter dispersion, and stagnant zone removal.",
    description: [
      "Effective ventilation is critical to maintaining safe and productive underground mining operations. Complex mine geometries, long ventilation routes, equipment heat loads, dust generation, and contaminant sources can create inadequate airflow, recirculation, excessive pressure losses, and poorly ventilated working zones.",
      "MACPROTEC applies advanced CFD simulations to analyze three-dimensional airflow, pressure distribution, heat transport, and contaminant movement throughout mine ventilation systems. Our analyses help identify ventilation deficiencies, optimize air distribution, evaluate fan and duct performance, and assess proposed ventilation modifications before implementation.",
    ],
    applications: [
      "Underground Mine Workings",
      "Tunnels & Development Drifts",
      "Shafts & Raises",
      "Ventilation Airways",
      "Mining Faces",
      "Equipment Chambers",
      "Auxiliary Ventilation Systems",
      "Refuge & Underground Facilities",
    ],
    keyAnalyses: [
      "Airflow velocity and distribution analysis",
      "Mine pressure and ventilation resistance assessment",
      "Fresh-air distribution and return-air path evaluation",
      "Ventilation fan performance and airflow balancing",
      "Recirculation and stagnant-air zone identification",
      "Heat accumulation and thermal environment assessment",
      "Dust, gas, and contaminant transport analysis",
      "Auxiliary fan and ventilation duct performance",
      "Ventilation effectiveness at active working faces",
      "Evaluation of alternative ventilation layouts and operating scenarios",
    ],
    deliverables: [
      "Airflow velocity and pressure contour visualizations",
      "Ventilation airflow distribution assessment",
      "Recirculation and stagnant-zone identification",
      "Temperature and heat distribution maps",
      "Dust and contaminant dispersion results",
      "Fan and auxiliary ventilation performance assessment",
      "Comparative evaluation of ventilation scenarios",
      "Engineering recommendations for system optimization",
    ],
    keyBenefits: [
      "Improve fresh-air distribution to critical working areas",
      "Eliminate poorly ventilated and stagnant-air zones",
      "Improve removal of heat, dust, and airborne contaminants",
      "Reduce ventilation pressure losses and energy consumption",
      "Optimize main and auxiliary ventilation performance",
      "Improve working conditions in underground operations",
      "Support mine expansion and ventilation modification studies",
      "Validate ventilation strategies before implementation",
      "Enhance overall mine safety and operational reliability",
    ],
  },
  {
    id: "06",
    slug: "pneumatic-conveying-and-gas-solid-flow-analysis",
    title: "Pneumatic Conveying & Gas-Solid Flow Analysis",
    badge: "PNEUMATIC TRANSPORT",
    image: "/images/cfd-engineering/mining/service_06.jpg",
    shortDescription:
      "Particle-gas CFD modeling to evaluate conveying velocities, pressure losses, particle deposition, and bend erosion in mineral powder transfer pipelines.",
    description: [
      "Pneumatic conveying systems are widely used in mining and mineral processing to transport fine powders, mineral concentrates, dust, and other particulate materials using air or process gas. Poor gas-solid distribution, inadequate conveying velocity, excessive pressure losses, particle deposition, and high impact velocities can result in pipeline blockage, erosion, unstable conveying, and excessive energy consumption.",
      "MACPROTEC applies advanced CFD and particle-flow modeling to simulate gas-solid transport throughout pneumatic conveying systems. Our analyses evaluate particle trajectories, solids distribution, pressure drop, conveying velocity, and particle-wall interactions to identify system limitations and optimize conveying performance for reliable and energy-efficient material transport.",
    ],
    applications: [
      "Mineral Fines Conveying",
      "Concentrate Transport",
      "Dust Transport Systems",
      "Powder & Additive Handling",
      "Pneumatic Transfer Lines",
      "Silo Feeding Systems",
      "Collector Dust Return Systems",
      "Fine Material Distribution Networks",
    ],
    keyAnalyses: [
      "Gas-solid flow distribution analysis",
      "Particle velocity and trajectory prediction",
      "Pressure drop and system resistance evaluation",
      "Minimum conveying velocity assessment",
      "Particle deposition and accumulation analysis",
      "Pipeline blockage and plugging risk assessment",
      "Particle-wall impact and erosion prediction",
      "Solids loading and concentration distribution",
      "Flow behavior through bends, tees, and branches",
      "Dense and dilute phase conveying assessment",
      "Pipeline geometry and operating condition optimization",
    ],
    deliverables: [
      "Gas velocity and pressure contour visualizations",
      "Particle trajectory and solids concentration maps",
      "Conveying pressure drop and system performance assessment",
      "Particle deposition and blockage-risk identification",
      "Erosion and high-impact zone prediction",
      "Conveying velocity and solids loading assessment",
      "Comparative evaluation of operating and design scenarios",
      "Engineering recommendations for conveying system optimization",
    ],
    keyBenefits: [
      "Improve conveying efficiency and system reliability",
      "Reduce pipeline blockage and material deposition",
      "Minimize erosion and premature equipment wear",
      "Reduce pressure losses and conveying energy consumption",
      "Maintain stable transport of fine mineral materials",
      "Improve material distribution across conveying networks",
      "Increase conveying capacity and operating flexibility",
      "Reduce maintenance requirements and unplanned downtime",
      "Support system debottlenecking and capacity expansion",
    ],
  },
  {
    id: "07",
    slug: "erosion-and-wear-analysis",
    title: "Erosion & Wear Analysis",
    badge: "EROSION & WEAR",
    image: "/images/cfd-engineering/mining/service_07.jpg",
    shortDescription:
      "Quantitative prediction of abrasive particle impingement, wall shear, wear rate contours (mm/year), and liner life in slurry pipes, pumps, and chutes.",
    description: [
      "Mining and mineral processing equipment is continuously exposed to abrasive slurries, high-velocity particles, and particle-laden flows that can cause severe erosion and progressive material loss. Localized wear in pipelines, bends, hydrocyclones, valves, chutes, and other process equipment can shorten equipment life, increase maintenance requirements, and lead to unexpected failures and production interruptions.",
      "MACPROTEC applies advanced CFD and particle-tracking simulations to predict particle trajectories, impact velocity, impact angle, wall shear, and erosion-prone regions under actual operating conditions. Our analyses identify the mechanisms responsible for localized wear and evaluate geometry, material, and operating modifications to reduce erosion and extend equipment service life.",
    ],
    applications: [
      "Slurry Pipelines & Bends",
      "Hydrocyclones",
      "Pumps & Valves",
      "Chutes & Transfer Points",
      "Manifolds & Headers",
      "Slurry Distribution Systems",
      "Nozzles & Reducers",
      "Mineral Processing Equipment",
    ],
    keyAnalyses: [
      "Particle trajectory and wall-impact analysis",
      "Erosion rate and wear-pattern prediction",
      "Particle impact velocity and impact angle assessment",
      "High-velocity and high-turbulence zone identification",
      "Slurry and particle concentration distribution",
      "Localized wall shear and flow behavior analysis",
      "Erosion assessment at bends, tees, reducers, and fittings",
      "Influence of particle size, concentration, and material properties",
      "Geometry modification and wear-reduction assessment",
      "Comparison of operating conditions and design alternatives",
    ],
    deliverables: [
      "Erosion and wear-rate contour maps",
      "Particle trajectory and impact visualizations",
      "High-wear and critical-location identification",
      "Impact velocity and angle distribution assessment",
      "Relative erosion comparison between design alternatives",
      "Assessment of geometry and operating-condition modifications",
      "Engineering recommendations for wear mitigation",
      "Technical CFD report with actionable recommendations",
    ],
    keyBenefits: [
      "Identify erosion-prone areas before equipment failure",
      "Reduce excessive and localized material wear",
      "Extend pipeline and equipment service life",
      "Reduce maintenance frequency and replacement costs",
      "Minimize unexpected failures and production downtime",
      "Optimize equipment geometry to reduce particle impact",
      "Support selection and placement of wear protection",
      "Validate modifications before implementation",
      "Improve overall equipment reliability and plant availability",
    ],
  },
  {
    id: "08",
    slug: "root-cause-cfd-investigation",
    title: "Root Cause CFD Investigation",
    badge: "FAILURE DIAGNOSTICS",
    image: "/images/cfd-engineering/mining/service_08.jpg",
    shortDescription:
      "Systematic multi-physics CFD investigation to isolate physical failure mechanisms, slurry settling, chute clogging, and unexpected pressure drops.",
    description: [
      "Recurring performance problems in mining and mineral processing systems are often driven by complex interactions between fluid flow, slurry behavior, particle transport, pressure distribution, and equipment geometry. Issues such as repeated blockages, excessive wear, poor separation, dust escape, slurry settling, and unexpected pressure losses can be difficult to diagnose using plant measurements and conventional engineering calculations alone.",
      "MACPROTEC applies advanced CFD, multiphase, and particle-flow simulations to recreate actual operating conditions and identify the physical mechanisms responsible for these problems. By comparing plant data with simulation results, we isolate the root cause, quantify its impact, and evaluate corrective modifications before implementation.",
    ],
    applications: [
      "Slurry Transport Systems",
      "Hydrocyclones",
      "Pneumatic Conveying",
      "Dust Extraction Systems",
      "Mine Ventilation",
      "Chutes & Transfer Points",
      "Pumps & Piping",
      "Mineral Processing Equipment",
    ],
    keyAnalyses: [
      "Abnormal pressure loss and flow restriction investigation",
      "Slurry settling and solids accumulation assessment",
      "Particle deposition and blockage analysis",
      "Flow maldistribution and recirculation identification",
      "Erosion and localized wear investigation",
      "Hydrocyclone and separation performance assessment",
      "Dust escape and extraction deficiency analysis",
      "Ventilation airflow and stagnant-zone investigation",
      "Comparison of actual versus design operating conditions",
      "Evaluation of corrective modifications and operating scenarios",
    ],
    deliverables: [
      "Root cause CFD investigation report",
      "Flow, pressure, particle, and phase-distribution visualizations",
      "Identification of performance-limiting mechanisms",
      "Quantification of pressure loss, deposition, erosion, or maldistribution",
      "Comparison of actual and expected system performance",
      "Comparative assessment of corrective alternatives",
      "Engineering recommendations and remedial actions",
      "Technical guidance for implementation",
    ],
    keyBenefits: [
      "Identify the true cause of recurring operational problems",
      "Reduce repeated troubleshooting and ineffective modifications",
      "Eliminate flow restrictions, deposition, and process bottlenecks",
      "Reduce excessive erosion and equipment wear",
      "Improve separation, conveying, and ventilation performance",
      "Reduce unplanned downtime and production losses",
      "Validate corrective solutions before plant implementation",
      "Reduce maintenance and modification costs",
      "Improve long-term equipment reliability and plant performance",
    ],
  },
];
