export interface OilGasService {
  id: string;
  slug: string;
  title: string;
  badge: string;
  image: string;
  shortDescription: string;
  description: string[];
  applications: string[];
  keyAnalyses: string[];
  deliverables: string[];
  keyBenefits: string[];
}

export const OILGAS_SERVICES: OilGasService[] = [
  {
    id: "01",
    slug: "flow-assurance-and-pipeline-analysis",
    title: "Flow Assurance & Pipeline Analysis",
    badge: "PIPELINES & FLOW",
    image: "/images/cfd-engineering/oil-gas/service_01.jpg",
    shortDescription:
      "Advanced CFD and hydraulic simulation to evaluate pressure losses, fluid holdup, slugging, and flow restrictions across upstream, midstream, and subsea pipelines.",
    description: [
      "Reliable transportation of oil, gas, and multiphase fluids is critical to the safe and efficient operation of upstream, midstream, and processing facilities. Changes in pressure, temperature, fluid composition, and operating conditions can lead to excessive pressure losses, liquid accumulation, slugging, unstable flow, and reduced pipeline capacity.",
      "MACPROTEC applies advanced CFD and engineering analysis to evaluate fluid behavior throughout pipelines, risers, manifolds, and gathering systems. Our studies assess hydraulic performance, flow regimes, pressure and temperature profiles, and transient behavior to identify flow restrictions, optimize operating conditions, and support reliable pipeline design and operation.",
    ],
    applications: [
      "Oil & Gas Pipelines",
      "Multiphase Gathering Lines",
      "Subsea Pipelines & Risers",
      "Production Flowlines",
      "Gas Transmission Systems",
      "Manifolds & Headers",
      "Pipeline Tie-ins",
      "Transfer & Export Lines",
    ],
    keyAnalyses: [
      "Pressure drop and hydraulic performance analysis",
      "Multiphase flow regime assessment",
      "Liquid holdup and accumulation prediction",
      "Slug formation and severe slugging analysis",
      "Velocity and flow distribution evaluation",
      "Pipeline capacity and bottleneck assessment",
      "Transient start-up and shutdown analysis",
      "Erosion and high-velocity region assessment",
      "Pipeline routing, diameter, and operating scenario evaluation",
    ],
    deliverables: [
      "Pressure, temperature, and velocity profiles",
      "Flow regime and liquid holdup assessment",
      "Pipeline pressure drop and capacity calculations",
      "Slugging and transient flow evaluation",
      "Bottleneck and flow restriction identification",
      "Comparative analysis of operating and design scenarios",
      "Engineering recommendations for pipeline optimization",
      "Technical report with actionable engineering solutions",
    ],
    keyBenefits: [
      "Improve pipeline capacity and transportation efficiency",
      "Reduce excessive pressure losses",
      "Minimize slugging and unstable flow conditions",
      "Reduce liquid accumulation and operational disruptions",
      "Identify pipeline bottlenecks before modifications",
      "Improve system reliability and operating flexibility",
      "Support pipeline sizing, debottlenecking, and expansion studies",
      "Reduce operating risk and lifecycle costs",
    ],
  },
  {
    id: "02",
    slug: "multiphase-flow-cfd-analysis",
    title: "Multiphase Flow CFD Analysis",
    badge: "MULTIPHASE PHYSICS",
    image: "/images/cfd-engineering/oil-gas/service_02.jpg",
    shortDescription:
      "Simulation of complex phase interactions (gas, oil, water, particles) under realistic operating conditions to optimize equipment, reduce erosion, and prevent liquid holdup.",
    description: [
      "Multiphase flow is a fundamental challenge in oil and gas production and processing, where gas, oil, water, and sometimes solid particles flow simultaneously through pipelines and process equipment. Differences in phase velocity and density can result in phase separation, liquid accumulation, slugging, flow instability, erosion, and uneven distribution, affecting production capacity and equipment reliability.",
      "MACPROTEC applies advanced multiphase CFD modeling to simulate complex phase interactions under realistic operating conditions. Our analyses provide detailed insight into phase distribution, flow regimes, liquid holdup, interface behavior, and transient phenomena, helping optimize equipment and piping systems, troubleshoot operational problems, and improve overall process performance.",
    ],
    applications: [
      "Production Flowlines",
      "Subsea Pipelines & Risers",
      "Wellhead & Gathering Systems",
      "Separators & Scrubbers",
      "Manifolds & Headers",
      "Slug Catchers",
      "Process Piping",
      "Gas-Liquid Distribution Systems",
    ],
    keyAnalyses: [
      "Gas-liquid and liquid-liquid flow behavior",
      "Multiphase flow regime assessment",
      "Phase distribution and volume fraction analysis",
      "Liquid holdup and accumulation prediction",
      "Slug formation and transient flow behavior",
      "Phase velocity and slip velocity evaluation",
      "Flow separation and interface behavior analysis",
      "Erosion risk from particle-laden multiphase flow",
      "Operating and design scenario comparison",
    ],
    deliverables: [
      "Phase distribution and volume fraction contours",
      "Gas and liquid velocity visualizations",
      "Liquid holdup and accumulation assessment",
      "Flow regime and slugging evaluation",
      "Pressure and phase distribution profiles",
      "Erosion and high-velocity region assessment",
      "Comparative evaluation of design alternatives",
      "Engineering recommendations for system optimization",
    ],
    keyBenefits: [
      "Improve understanding of complex multiphase flow behavior",
      "Reduce slugging and flow instability",
      "Minimize liquid accumulation and phase maldistribution",
      "Improve pipeline and process equipment performance",
      "Reduce erosion and equipment degradation risks",
      "Support production capacity and debottlenecking studies",
      "Validate design modifications before implementation",
      "Improve operational reliability and production efficiency",
    ],
  },
  {
    id: "03",
    slug: "separator-and-process-vessel-analysis",
    title: "Separator & Process Vessel Analysis",
    badge: "SEPARATION SYSTEMS",
    image: "/images/cfd-engineering/oil-gas/service_03.jpg",
    shortDescription:
      "Detailed CFD simulation of internal flow patterns, gas-liquid disengagement, droplet trajectories, and internals performance inside oil/gas process vessels.",
    description: [
      "Efficient phase separation and controlled internal flow are critical to the performance of oil and gas processing facilities. Poor inlet distribution, excessive turbulence, short-circuiting, inadequate residence time, liquid carryover, gas carry-under, and ineffective internals can significantly reduce separation efficiency and limit equipment capacity.",
      "MACPROTEC applies advanced CFD and engineering analysis to evaluate multiphase flow behavior inside separators and process vessels. Our simulations provide detailed insight into gas-liquid distribution, phase separation, droplet behavior, residence time, pressure drop, and internal flow patterns. The analysis supports vessel design, debottlenecking, troubleshooting, and optimization of existing separator internals.",
    ],
    applications: [
      "Two-Phase Separators",
      "Three-Phase Separators",
      "Gas Scrubbers",
      "Knock-Out Drums",
      "Slug Catchers",
      "Inlet Separators",
      "Flash Drums",
      "Process Vessels",
    ],
    keyAnalyses: [
      "Gas-liquid and oil-water phase distribution analysis",
      "Separation efficiency and phase disengagement assessment",
      "Droplet trajectory and size distribution analysis",
      "Liquid carryover and gas carry-under prediction",
      "Residence time and flow uniformity evaluation",
      "Inlet momentum and turbulence assessment",
      "Short-circuiting, recirculation, and dead-zone identification",
      "Pressure drop across vessel internals",
      "Demister, vane pack, baffle, and inlet-device performance",
      "Vessel capacity and debottlenecking assessment",
    ],
    deliverables: [
      "Phase distribution and velocity contour visualizations",
      "Separation efficiency assessment",
      "Droplet trajectory and carryover analysis",
      "Residence time and flow distribution evaluation",
      "Vessel internal performance assessment",
      "Pressure drop and hydraulic performance results",
      "Comparative evaluation of internal configurations",
      "Engineering recommendations for vessel optimization",
    ],
    keyBenefits: [
      "Improve oil, gas, and water separation efficiency",
      "Reduce liquid carryover and gas carry-under",
      "Increase effective vessel capacity and throughput",
      "Improve performance of separator internals",
      "Eliminate short-circuiting and unfavorable recirculation",
      "Reduce downstream equipment contamination and loading",
      "Support separator debottlenecking and retrofit projects",
      "Validate internal modifications before implementation",
      "Improve process stability and overall equipment reliability",
    ],
  },
  {
    id: "04",
    slug: "thermal-and-heat-transfer-analysis",
    title: "Thermal & Heat Transfer Analysis",
    badge: "THERMAL & HEAT LOSS",
    image: "/images/cfd-engineering/oil-gas/service_04.jpg",
    shortDescription:
      "Evaluation of temperature distribution, thermal insulation, heat loss, and transient heating/cooling across pipelines, LNG systems, and storage facilities.",
    description: [
      "Thermal performance is a critical aspect of oil and gas production, transportation, and processing. Pipelines, process vessels, heat exchangers, heaters, LNG systems, and storage facilities operate under conditions where temperature variation, heat loss, thermal gradients, and inadequate cooling or heating can affect fluid properties, process efficiency, equipment integrity, and operational reliability.",
      "MACPROTEC applies advanced CFD and thermal analysis to evaluate temperature distribution, heat transfer, thermal losses, and cooling or heating performance under realistic operating conditions. Our studies support equipment design, insulation optimization, thermal debottlenecking, and investigation of temperature-related process limitations across oil and gas facilities.",
    ],
    applications: [
      "Oil & Gas Pipelines",
      "Process Vessels",
      "Heat Exchangers",
      "Fired Heaters",
      "LNG & Cryogenic Systems",
      "Storage Tanks",
      "Cooling Systems",
      "Heated Transfer Lines",
    ],
    keyAnalyses: [
      "Temperature distribution and thermal mapping",
      "Convective, conductive, and radiative heat transfer analysis",
      "Heat loss and insulation performance assessment",
      "Thermal gradient and hot/cold spot identification",
      "Pipeline cooling and heating behavior",
      "Heat exchanger thermal performance evaluation",
      "Transient heating and cooling analysis",
      "LNG and cryogenic thermal behavior assessment",
      "Evaluation of thermal design modifications and operating scenarios",
    ],
    deliverables: [
      "Temperature contour and thermal distribution plots",
      "Heat flux and heat loss assessment",
      "Insulation performance evaluation",
      "Thermal gradient and hot/cold spot analysis",
      "Pipeline and equipment thermal performance results",
      "Comparative assessment of operating and design alternatives",
      "Engineering recommendations for thermal optimization",
      "Technical report with actionable engineering solutions",
    ],
    keyBenefits: [
      "Improve thermal efficiency and process performance",
      "Reduce heat losses and energy consumption",
      "Maintain required process and fluid temperatures",
      "Improve insulation and thermal management strategies",
      "Reduce temperature-related operational problems",
      "Protect equipment from excessive thermal gradients",
      "Support pipeline, LNG, and process equipment design",
      "Improve equipment reliability and service life",
      "Reduce operating costs through optimized thermal performance",
    ],
  },
  {
    id: "05",
    slug: "heat-exchanger-performance-and-flow-distribution-analysis",
    title: "Heat Exchanger Performance & Flow Distribution Analysis",
    badge: "HEAT EXCHANGERS",
    image: "/images/cfd-engineering/oil-gas/service_05.jpg",
    shortDescription:
      "CFD modeling of shell-side and tube-side flow distribution, pressure drops, thermal effectiveness, and fouling mitigation in exchangers and headers.",
    description: [
      "Heat exchangers are critical to thermal efficiency, process stability, and energy recovery across oil and gas facilities. Poor inlet distribution, bypass flow, recirculation, fouling, excessive pressure drop, and uneven velocity profiles can significantly reduce heat transfer performance and increase operating costs.",
      "MACPROTEC applies CFD and thermal analysis to evaluate flow distribution, temperature profiles, pressure losses, and heat transfer performance inside heat exchangers and associated headers. Our studies help identify maldistribution, optimize nozzle and header configurations, improve thermal effectiveness, and support debottlenecking or retrofit decisions.",
    ],
    applications: [
      "Shell-and-Tube Heat Exchangers",
      "Air-Cooled Heat Exchangers",
      "Plate Heat Exchangers",
      "LNG Heat Exchangers",
      "Waste Heat Recovery Exchangers",
      "Process Coolers & Heaters",
      "Exchanger Headers & Manifolds",
      "Condensers & Reboilers",
    ],
    keyAnalyses: [
      "Inlet and outlet flow distribution analysis",
      "Tube-side and shell-side velocity distribution",
      "Thermal performance and heat transfer effectiveness",
      "Pressure drop and hydraulic resistance evaluation",
      "Flow maldistribution and bypass identification",
      "Recirculation and stagnant zone assessment",
      "Header, nozzle, and distributor performance analysis",
      "Fouling-prone region identification",
      "Operating scenario and design modification comparison",
    ],
    deliverables: [
      "Velocity, pressure, and temperature contour visualizations",
      "Flow distribution and maldistribution assessment",
      "Heat transfer performance evaluation",
      "Pressure drop and hydraulic performance report",
      "Identification of bypass and low-flow regions",
      "Header and nozzle performance assessment",
      "Comparative evaluation of design alternatives",
      "Engineering recommendations for exchanger optimization",
    ],
    keyBenefits: [
      "Improve heat transfer efficiency",
      "Reduce flow maldistribution and bypass",
      "Lower pressure losses and pumping requirements",
      "Improve exchanger thermal duty and capacity",
      "Reduce fouling tendency and maintenance frequency",
      "Increase equipment reliability and service life",
      "Support exchanger retrofit and debottlenecking projects",
      "Improve overall process efficiency and energy utilization",
    ],
  },
  {
    id: "06",
    slug: "flare-combustion-and-gas-dispersion-analysis",
    title: "Flare, Combustion & Gas Dispersion Analysis",
    badge: "FLARE & COMBUSTION",
    image: "/images/cfd-engineering/oil-gas/service_06.jpg",
    shortDescription:
      "Simulation of flare combustion aerodynamics, thermal radiation exposure, plume dispersion, and accidental toxic/flammable gas releases for safety.",
    description: [
      "Flare and combustion systems are critical for the safe disposal of hydrocarbon gases during normal operation, start-up, shutdown, and emergency relief events. Poor combustion performance, flame instability, excessive thermal radiation, incomplete combustion, or unfavorable gas dispersion can create safety, environmental, and operational risks around oil and gas facilities.",
      "MACPROTEC applies advanced CFD simulations to evaluate flare combustion, flame behavior, thermal radiation, exhaust dispersion, and accidental gas releases under realistic operating and atmospheric conditions. Our analyses support flare system optimization, hazardous-area assessment, safe equipment layout, and evaluation of potential impacts on personnel and surrounding facilities.",
    ],
    applications: [
      "Flare Systems & Flare Tips",
      "Flare Stacks",
      "Fired Heaters & Burners",
      "Thermal Oxidizers",
      "Gas Processing Facilities",
      "LNG Facilities",
      "Offshore Platforms",
      "Emergency Gas Releases",
    ],
    keyAnalyses: [
      "Flare flame shape and stability assessment",
      "Fuel-air mixing and combustion efficiency analysis",
      "Flame temperature and heat release distribution",
      "Thermal radiation and heat flux assessment",
      "Combustion species and emission distribution",
      "Gas release and atmospheric dispersion modeling",
      "Flammable and toxic gas concentration analysis",
      "Wind direction and atmospheric condition assessment",
      "Interaction of gas plumes with buildings and equipment",
      "Evaluation of flare and facility layout modifications",
    ],
    deliverables: [
      "Flame and temperature contour visualizations",
      "Thermal radiation and heat flux maps",
      "Gas concentration and dispersion contours",
      "Flammable/toxic gas cloud extent assessment",
      "Combustion performance evaluation",
      "Wind and operating scenario comparison",
      "Identification of potentially affected plant areas",
      "Engineering recommendations for system and layout improvement",
    ],
    keyBenefits: [
      "Improve flare combustion performance and stability",
      "Reduce thermal radiation exposure to personnel and equipment",
      "Identify hazardous gas accumulation and dispersion zones",
      "Improve understanding of accidental gas release scenarios",
      "Support safer equipment positioning and facility layout",
      "Reduce incomplete combustion and associated emissions",
      "Validate flare and mitigation modifications before implementation",
      "Enhance overall process safety and operational reliability",
    ],
  },
  {
    id: "07",
    slug: "pipe-stress-analysis-and-support-design",
    title: "Pipe Stress Analysis & Support Design",
    badge: "PIPING INTEGRITY",
    image: "/images/cfd-engineering/oil-gas/service_07.jpg",
    shortDescription:
      "Stress analysis and support layout engineering under thermal expansion, pressure, nozzle overloads, and dynamic slugging in accordance with ASME codes.",
    description: [
      "Piping systems in oil and gas facilities operate under demanding combinations of pressure, temperature, weight, thermal expansion, equipment movement, and occasional loading. Inadequate piping flexibility or poorly designed supports can result in excessive stresses, high equipment nozzle loads, vibration, leakage, fatigue damage, and premature piping or equipment failure.",
      "MACPROTEC performs comprehensive pipe stress analysis and support design to verify piping system integrity under operating, start-up, shutdown, and upset conditions. Our engineering studies evaluate thermal expansion, sustained and occasional loads, equipment interfaces, and support behavior to develop safe and practical piping configurations in accordance with applicable industry codes and standards.",
    ],
    applications: [
      "Process Piping Systems",
      "Oil & Gas Pipelines",
      "Compressor & Pump Piping",
      "High-Temperature Piping",
      "Flare & Relief Piping",
      "LNG & Cryogenic Piping",
      "Tank Farm Piping",
      "Offshore & Modular Piping",
    ],
    keyAnalyses: [
      "Sustained, thermal, and occasional stress evaluation",
      "Thermal expansion and piping flexibility analysis",
      "Equipment nozzle load assessment",
      "Pump and compressor piping load evaluation",
      "Support load and displacement analysis",
      "Wind and seismic load assessment",
      "Relief, slug, and other dynamic load evaluation where applicable",
      "Flange and connection integrity assessment",
      "Piping routing and flexibility optimization",
      "Code compliance assessment for applicable piping systems",
    ],
    deliverables: [
      "Pipe stress calculation report",
      "Piping displacement and stress results",
      "Equipment nozzle load assessment",
      "Support reaction and load summary",
      "Support location and type recommendations",
      "Spring hanger/restraint requirements where applicable",
      "Stress-critical piping identification",
      "Recommended routing and support modifications",
      "Code compliance summary",
    ],
    keyBenefits: [
      "Ensure piping integrity and code compliance",
      "Prevent overstress and excessive deformation",
      "Protect pumps, compressors, vessels, and other connected equipment",
      "Reduce excessive nozzle and support loads",
      "Accommodate thermal expansion safely",
      "Minimize fatigue, leakage, and premature piping failures",
      "Optimize support arrangements and piping flexibility",
      "Improve system reliability, maintainability, and operating safety",
    ],
  },
  {
    id: "08",
    slug: "pressure-vessel-storage-tank-and-structural-fea",
    title: "Pressure Vessel, Storage Tank & Structural FEA",
    badge: "STRUCTURAL FEA",
    image: "/images/cfd-engineering/oil-gas/service_08.jpg",
    shortDescription:
      "Finite Element Analysis (FEA) of stress concentration, thermal-mechanical fatigue, buckling, and nozzle loads in pressure vessels and storage tanks.",
    description: [
      "Pressure vessels, storage tanks, and supporting structures in oil and gas facilities are subjected to complex combinations of internal or external pressure, operating temperature, fluid weight, wind, seismic forces, nozzle loads, and other mechanical loads. Localized stress concentrations, excessive deformation, buckling, or fatigue can compromise equipment integrity and reduce service life.",
      "MACPROTEC applies advanced Finite Element Analysis (FEA) to evaluate the structural and thermal-mechanical behavior of critical oil and gas equipment under realistic operating and design conditions. Our analyses support new equipment design, modification and retrofit projects, fitness evaluation, and investigation of structural concerns while verifying compliance with applicable engineering codes and design criteria.",
    ],
    applications: [
      "Pressure Vessels",
      "Storage Tanks",
      "Process Columns & Drums",
      "Reactors & Separators",
      "Equipment Skids",
      "Nozzles & Connections",
      "Equipment Support Structures",
      "Platforms & Structural Frames",
    ],
    keyAnalyses: [
      "Static structural stress and deformation analysis",
      "Internal and external pressure assessment",
      "Thermal stress and coupled thermal-structural analysis",
      "Local stress concentration evaluation",
      "Nozzle, opening, and reinforcement assessment",
      "Buckling and stability analysis",
      "Wind and seismic load evaluation",
      "Fatigue and cyclic loading assessment",
      "Support, saddle, skirt, and anchorage analysis",
      "Evaluation of equipment modifications and reinforcement options",
    ],
    deliverables: [
      "Stress, strain, and deformation contour plots",
      "Thermal and structural FEA results",
      "Critical stress and high-deformation zone identification",
      "Nozzle and connection assessment",
      "Buckling and stability evaluation",
      "Fatigue assessment where applicable",
      "Design modification and reinforcement recommendations",
      "Engineering calculation and FEA report",
    ],
    keyBenefits: [
      "Verify structural integrity under design and operating loads",
      "Identify critical stresses before equipment failure",
      "Reduce risk of deformation, buckling, and fatigue damage",
      "Support safe equipment modification and retrofit projects",
      "Optimize material thickness and structural reinforcement",
      "Extend equipment service life",
      "Reduce unnecessary modifications through detailed numerical assessment",
      "Improve equipment safety, reliability, and maintainability",
    ],
  },
  {
    id: "09",
    slug: "root-cause-engineering-investigation",
    title: "Root Cause Engineering Investigation",
    badge: "FAILURE DIAGNOSTICS",
    image: "/images/cfd-engineering/oil-gas/service_09.jpg",
    shortDescription:
      "Systematic multi-physics investigation (CFD + FEA + process analytics) to diagnose recurring operational failures, erosion, vibration, and hot spots.",
    description: [
      "Recurring operational and equipment problems in oil and gas facilities are often caused by complex interactions between fluid flow, pressure, temperature, multiphase behavior, piping stresses, vibration, and equipment geometry. Problems such as unexpected pressure losses, poor separation, erosion, vibration, thermal hot spots, and repeated equipment failures may be difficult to diagnose using plant measurements or conventional calculations alone.",
      "MACPROTEC combines CFD, FEA, process data, and engineering analysis to systematically investigate these problems and identify their underlying physical causes. By recreating actual operating conditions and evaluating potential failure mechanisms, we help distinguish symptoms from root causes and develop practical corrective solutions that can be assessed before plant implementation.",
    ],
    applications: [
      "Piping & Pipeline Systems",
      "Separators & Process Vessels",
      "Pumps & Compressors",
      "Heat Exchangers",
      "Flare Systems",
      "Storage Tanks",
      "Process Equipment",
      "Gas & Liquid Handling Systems",
    ],
    keyAnalyses: [
      "Abnormal pressure loss and flow restriction investigation",
      "Flow maldistribution and recirculation assessment",
      "Multiphase flow and liquid accumulation analysis",
      "Erosion, impingement, and localized high-velocity assessment",
      "Thermal hot spot and temperature anomaly investigation",
      "Piping stress and excessive equipment nozzle load assessment",
      "Flow-induced vibration and instability investigation",
      "Equipment underperformance and capacity limitation assessment",
      "Comparison of actual versus design operating conditions",
      "Evaluation of corrective modifications and alternative solutions",
    ],
    deliverables: [
      "Root cause investigation report",
      "CFD and/or FEA simulation results",
      "Identification of primary failure or performance mechanisms",
      "Flow, pressure, temperature, stress, or erosion visualizations",
      "Quantification of performance-limiting factors",
      "Comparative assessment of corrective alternatives",
      "Engineering recommendations and remedial actions",
      "Technical guidance for implementation",
    ],
    keyBenefits: [
      "Identify the underlying cause of recurring operational problems",
      "Avoid repeated troubleshooting of symptoms",
      "Reduce unplanned shutdowns and production losses",
      "Prevent recurring equipment and piping failures",
      "Improve equipment reliability and process stability",
      "Reduce maintenance and corrective modification costs",
      "Validate proposed solutions before implementation",
      "Support evidence-based engineering decisions",
      "Improve long-term safety, reliability, and plant performance",
    ],
  },
];
