export interface PowerService {
  id: string;
  slug: string;
  title: string;
  badge: string;
  image: string;
  shortDescription: string;
  description: string[];
  applications: string[];
  keyAnalyses: string[];
  deliverables: string[];
  keyBenefits: string[];
}

export const POWER_SERVICES: PowerService[] = [
  {
    id: "01",
    slug: "flow-and-pressure-analysis",
    title: "Flow & Pressure CFD Analysis",
    badge: "FLUID DYNAMICS",
    image: "/images/power/service-01.jpg",
    shortDescription:
      "Gas and fluid flow modeling across boilers, HRSGs, flue gas ducts, air intake systems, fans, and stacks to eliminate bottlenecks and balance draft systems.",
    description: [
      "Efficient fluid flow management is fundamental to the safe, reliable, and efficient operation of power generation facilities. Boilers, flue gas ducts, heat recovery systems, cooling circuits, and air handling networks rely on balanced flow and controlled pressure distribution to achieve optimal performance. Poor flow distribution, excessive pressure losses, recirculation zones, and flow imbalance can reduce plant efficiency, increase auxiliary power consumption, and accelerate equipment degradation.",
      "MACPROTEC utilizes advanced Computational Fluid Dynamics (CFD) to analyze airflow, flue gas flow, and pressure distribution throughout power generation systems. Our simulations identify hydraulic bottlenecks, optimize duct and piping configurations, improve fan and blower performance, and support engineering decisions that enhance plant efficiency, reliability, and operational stability.",
    ],
    applications: [
      "Boilers",
      "HRSGs (Heat Recovery Steam Generators)",
      "Flue Gas Ducts",
      "Air Intake Systems",
      "ID, FD & PA Fans",
      "Cooling Air Systems",
      "Chimneys & Stacks",
      "Waste Heat Recovery Systems",
    ],
    keyAnalyses: [
      "Flow distribution and velocity profile analysis",
      "Static and total pressure drop evaluation",
      "Fan operating point and system resistance assessment",
      "Flow balancing across duct and piping networks",
      "Identification of recirculation zones and flow separation",
      "Air leakage (false air) and bypass flow investigation",
      "Hydraulic bottleneck identification and debottlenecking studies",
      "Evaluation of design modifications and retrofit solutions",
    ],
    deliverables: [
      "CFD flow and pressure contour visualizations",
      "Velocity vectors and streamline plots",
      "Pressure drop and flow distribution reports",
      "Fan and duct performance assessment",
      "Engineering recommendations for system optimization",
      "Comparative evaluation of design alternatives",
      "Comprehensive technical report with actionable engineering solutions",
    ],
    keyBenefits: [
      "Improve airflow and flue gas distribution",
      "Reduce pressure losses and auxiliary power consumption",
      "Increase fan and blower efficiency",
      "Eliminate flow bottlenecks and recirculation zones",
      "Improve boiler and heat recovery system performance",
      "Enhance plant reliability and operational stability",
      "Support cost-effective retrofit and capacity improvement projects",
      "Minimize operating costs through optimized flow performance",
    ],
  },
  {
    id: "02",
    slug: "thermal-and-heat-transfer-analysis",
    title: "Thermal & Heat Transfer CFD Analysis",
    badge: "THERMAL & ENERGY",
    image: "/images/power/service-02.jpg",
    shortDescription:
      "Simulation of heat transfer, thermal radiation, and temperature distribution across boilers, superheaters, reheaters, HRSGs, economizers, and condensers.",
    description: [
      "Efficient heat transfer is critical to maximizing the performance, reliability, and efficiency of power generation systems. Boilers, furnaces, heat exchangers, HRSGs, condensers, and cooling equipment operate under demanding thermal conditions where uneven temperature distribution, excessive heat losses, and localized hot spots can reduce efficiency, increase fuel consumption, and shorten equipment life.",
      "MACPROTEC applies advanced Computational Fluid Dynamics (CFD) to simulate heat transfer, thermal radiation, and temperature distribution across critical power plant equipment. Our analyses help optimize thermal performance, improve heat recovery, reduce energy losses, and support engineering decisions for equipment upgrades and process improvements.",
    ],
    applications: [
      "Boilers",
      "HRSGs",
      "Superheaters & Reheaters",
      "Economizers",
      "Heat Exchangers",
      "Condensers",
      "Cooling Systems",
      "Waste Heat Recovery Systems",
    ],
    keyAnalyses: [
      "Temperature distribution and thermal mapping",
      "Heat transfer and thermal radiation analysis",
      "Heat loss and thermal leakage assessment",
      "Hot spot identification and thermal stress evaluation",
      "Heat exchanger thermal performance analysis",
      "Cooling system effectiveness assessment",
      "Transient heating and cooling simulations",
      "Evaluation of thermal design modifications",
    ],
    deliverables: [
      "Temperature contour and thermal distribution plots",
      "Heat flux and thermal radiation analysis reports",
      "Heat loss and hot spot assessment",
      "Heat exchanger and cooling system performance evaluation",
      "Engineering recommendations for thermal optimization",
      "Comparative evaluation of design alternatives",
      "Comprehensive technical report with actionable engineering solutions",
    ],
    keyBenefits: [
      "Improve thermal efficiency and plant performance",
      "Reduce fuel consumption and operating costs",
      "Minimize heat losses and thermal inefficiencies",
      "Eliminate thermal hot spots and uneven temperature distribution",
      "Improve heat recovery and equipment reliability",
      "Extend the service life of boilers and heat transfer equipment",
      "Support design improvements through virtual thermal validation",
      "Enhance overall plant efficiency and operational stability",
    ],
  },
  {
    id: "03",
    slug: "combustion-cfd-analysis",
    title: "Combustion CFD Analysis",
    badge: "COMBUSTION & FUELS",
    image: "/images/power/service-03.jpg",
    shortDescription:
      "Simulation of fuel-air mixing, flame development, heat release, species formation (NOx, CO), and temperature distribution in power boilers and burners.",
    description: [
      "Combustion performance directly influences fuel efficiency, heat release, emissions, and operational stability in thermal power generation. Poor fuel-air mixing, uneven burner distribution, flame instability, incomplete combustion, and localized high-temperature zones can increase fuel consumption, generate excessive CO and NOx emissions, cause slagging or fouling, and accelerate furnace degradation.",
      "MACPROTEC applies advanced combustion CFD to simulate fuel-air mixing, flame development, heat release, species formation, and temperature distribution under actual operating conditions. These simulations enable burner and furnace optimization, evaluation of different fuels and operating scenarios, and identification of combustion-related problems before implementing modifications in the plant.",
    ],
    applications: [
      "Pulverized Coal Combustion",
      "Gas & Oil-Fired Burners",
      "CFB & Biomass Combustion",
      "Waste-to-Energy Furnaces",
      "Low-NOx Burner Systems",
      "Fuel Conversion & Co-Firing",
      "Furnace Over-Fire Air Systems",
      "Start-up & Auxiliary Burners",
    ],
    keyAnalyses: [
      "Fuel-air mixing and combustion efficiency analysis",
      "Flame shape, stability, and flame penetration assessment",
      "Furnace temperature and heat release distribution",
      "O₂, CO, CO₂ and NOx species distribution",
      "Burner-to-burner flow and fuel distribution",
      "Excess air and combustion air optimization",
      "Slagging and high-temperature zone identification",
      "Alternative fuel and co-firing performance evaluation",
      "Burner configuration and operating scenario comparison",
    ],
    deliverables: [
      "Flame and temperature contour visualizations",
      "Fuel, air, and combustion species distribution plots",
      "Burner performance and combustion efficiency assessment",
      "CO, O₂ and NOx distribution analysis",
      "High-temperature and potential slagging zone identification",
      "Comparative assessment of operating/design scenarios",
      "Engineering recommendations for combustion optimization",
    ],
    keyBenefits: [
      "Improve combustion efficiency and fuel utilization",
      "Reduce fuel consumption and heat-rate losses",
      "Lower CO and NOx emissions",
      "Improve flame stability and furnace temperature uniformity",
      "Reduce incomplete combustion and unburnt fuel losses",
      "Minimize slagging, fouling, and localized overheating",
      "Support alternative fuel and co-firing strategies",
      "Improve boiler reliability and overall plant performance",
    ],
  },
  {
    id: "04",
    slug: "multiphase-and-particle-flow-analysis",
    title: "Multiphase & Particle Flow CFD Analysis",
    badge: "MULTIPHASE FLOW",
    image: "/images/power/service-04.jpg",
    shortDescription:
      "Multiphase simulation of gas-solid interactions, particle trajectories, dispersion, ash deposition, and erosion in coal, biomass, and CFB power boilers.",
    description: [
      "Power generation processes frequently involve the simultaneous transport of gases and solid particles, particularly in coal-fired, biomass, and waste-to-energy plants. Uneven particle distribution, poor fuel transport, ash deposition, erosion, and particle carryover can reduce combustion efficiency, restrict gas flow, damage equipment, and increase maintenance requirements.",
      "MACPROTEC applies advanced multiphase CFD techniques to simulate gas-solid interactions, particle trajectories, dispersion, deposition, and erosion throughout power generation systems. These analyses provide detailed insight into particle behavior and help optimize fuel transport, ash handling, separation equipment, and particle-laden gas systems for improved efficiency and reliability.",
    ],
    applications: [
      "Pulverized Coal Transport",
      "Biomass Particle Feeding",
      "Fly Ash Transport",
      "Bottom Ash Handling",
      "Cyclone Separation",
      "CFB Particle Circulation",
      "Fuel & Sorbent Injection",
      "Particle-Laden Flue Gas Systems",
    ],
    keyAnalyses: [
      "Gas-solid flow distribution analysis",
      "Particle trajectory and dispersion prediction",
      "Particle size and velocity distribution assessment",
      "Particle deposition and accumulation analysis",
      "Erosion and wear prediction",
      "Particle residence time evaluation",
      "Separation and collection efficiency analysis",
      "Fuel and sorbent particle distribution assessment",
      "Design and operating scenario comparison",
    ],
    deliverables: [
      "Gas-solid flow and particle trajectory visualizations",
      "Particle concentration and distribution maps",
      "Deposition and accumulation predictions",
      "Erosion and wear-risk maps",
      "Particle residence time and transport assessment",
      "Separation efficiency evaluation",
      "Comparative assessment of design alternatives",
      "Engineering recommendations for system optimization",
    ],
    keyBenefits: [
      "Improve fuel and particle distribution",
      "Reduce ash deposition and material build-up",
      "Minimize erosion and equipment wear",
      "Improve separation and collection efficiency",
      "Reduce material transport restrictions and blockages",
      "Enhance combustion and process performance",
      "Extend equipment service life and reduce maintenance",
      "Improve overall plant reliability and operating efficiency",
    ],
  },
  {
    id: "05",
    slug: "dust-collection-and-flue-gas-cleaning-analysis",
    title: "Dust Collection & Flue Gas Cleaning CFD Analysis",
    badge: "ENVIRONMENTAL & CLEANING",
    image: "/images/power/service-05.jpg",
    shortDescription:
      "CFD modeling of gas distribution, particulate transport, reagent mixing, and separation performance in ESPs, baghouses, SCRs, and FGD systems.",
    description: [
      "Effective dust collection and flue gas cleaning are critical for controlling particulate emissions, maintaining environmental compliance, and ensuring reliable operation of power generation facilities. Uneven gas distribution, excessive pressure drop, particle re-entrainment, poor reagent mixing, and localized high-velocity regions can significantly reduce pollution-control efficiency and increase fan power and maintenance requirements.",
      "MACPROTEC applies advanced CFD and particle-flow simulations to evaluate gas distribution, particulate transport, separation performance, and reagent mixing within flue gas cleaning systems. Our analyses identify performance limitations and support modifications that improve pollutant removal, reduce pressure losses, and enhance the reliability of emission-control equipment.",
    ],
    applications: [
      "Electrostatic Precipitators (ESP)",
      "Baghouse / Fabric Filters",
      "Cyclone & Multicyclone Separators",
      "Flue Gas Desulfurization (FGD)",
      "Selective Catalytic Reduction (SCR)",
      "Dry & Semi-Dry Scrubbers",
      "Sorbent Injection Systems",
      "Flue Gas Cleaning Ductwork",
    ],
    keyAnalyses: [
      "Flue gas velocity and flow uniformity analysis",
      "Particle trajectory, dispersion, and collection assessment",
      "Pressure drop and system resistance evaluation",
      "ESP and baghouse inlet flow distribution",
      "Particle deposition and re-entrainment analysis",
      "Reagent and sorbent mixing effectiveness",
      "SCR ammonia distribution and mixing analysis",
      "Scrubber gas-liquid interaction assessment",
      "Identification of bypass, recirculation, and high-velocity zones",
    ],
    deliverables: [
      "Gas velocity and pressure contour visualizations",
      "Particle trajectory and concentration maps",
      "Flow uniformity and distribution assessment",
      "Dust separation and collection efficiency evaluation",
      "Reagent/sorbent mixing performance assessment",
      "Pressure drop and system performance report",
      "Comparative assessment of design modifications",
      "Engineering recommendations for system optimization",
    ],
    keyBenefits: [
      "Improve particulate and pollutant removal efficiency",
      "Reduce emissions and support environmental compliance",
      "Improve ESP, baghouse, SCR, and FGD performance",
      "Reduce pressure losses and fan power consumption",
      "Improve reagent utilization and distribution",
      "Minimize particle deposition and re-entrainment",
      "Reduce equipment wear and maintenance requirements",
      "Improve overall reliability of flue gas cleaning systems",
    ],
  },
  {
    id: "06",
    slug: "cooling-system-and-cooling-tower-analysis",
    title: "Cooling System & Cooling Tower CFD Analysis",
    badge: "COOLING & HEAT REJECTION",
    image: "/images/power/service-06.jpg",
    shortDescription:
      "Simulation of airflow, heat/mass transfer, evaporation, hot-air recirculation, and ambient wind effects in natural draft, mechanical draft, and ACC cooling towers.",
    description: [
      "Cooling systems are critical to power plant efficiency because condenser performance and heat rejection directly influence turbine backpressure, generation efficiency, and plant output. Poor airflow distribution, cooling tower recirculation, hot-air re-ingestion, inadequate water distribution, or unfavorable wind conditions can reduce cooling capacity and significantly affect plant performance.",
      "MACPROTEC applies advanced CFD simulations to evaluate airflow, heat and mass transfer, evaporation, plume behavior, and thermal performance within cooling systems. Our analyses help identify cooling limitations, optimize equipment configuration, assess environmental effects, and improve heat rejection performance under different operating and ambient conditions.",
    ],
    applications: [
      "Natural Draft Cooling Towers",
      "Mechanical Draft Cooling Towers",
      "Air-Cooled Condensers (ACC)",
      "Cooling Tower Cells",
      "Cooling Water Distribution",
      "Condenser Cooling Systems",
      "Dry & Hybrid Cooling Systems",
      "Cooling Tower Plume Studies",
    ],
    keyAnalyses: [
      "Cooling airflow distribution and uniformity analysis",
      "Heat and mass transfer performance evaluation",
      "Hot-air recirculation and re-ingestion assessment",
      "Cooling tower thermal performance analysis",
      "Evaporation and water-air interaction modeling",
      "Ambient wind and crosswind impact assessment",
      "Cooling tower plume dispersion analysis",
      "ACC airflow and fan interaction assessment",
      "Performance evaluation under different ambient and load conditions",
    ],
    deliverables: [
      "Airflow, temperature, and humidity contour visualizations",
      "Cooling tower thermal performance assessment",
      "Hot-air recirculation and re-ingestion maps",
      "ACC airflow distribution and performance analysis",
      "Wind sensitivity and operating scenario comparison",
      "Cooling capacity and heat rejection assessment",
      "Engineering recommendations for cooling system optimization",
    ],
    keyBenefits: [
      "Improve cooling capacity and heat rejection performance",
      "Reduce condenser backpressure and improve turbine performance",
      "Minimize hot-air recirculation and re-ingestion",
      "Improve cooling tower and ACC efficiency",
      "Reduce sensitivity to adverse wind and ambient conditions",
      "Improve plant output during high-temperature conditions",
      "Support cooling system upgrades and capacity expansion",
      "Enhance overall power plant efficiency and operational reliability",
    ],
  },
  {
    id: "07",
    slug: "fan-and-duct-system-analysis",
    title: "Fan & Duct System Analysis",
    badge: "FAN & DUCT DYNAMICS",
    image: "/images/power/service-07.jpg",
    shortDescription:
      "CFD analysis of airflow distribution, pressure loss, system resistance, and fan operating behavior across ID, FD, and PA fan duct networks.",
    description: [
      "Fan and duct systems are essential for transporting combustion air, flue gas, cooling air, and process gases throughout power generation facilities. Excessive pressure losses, poor duct geometry, flow imbalance, recirculation, leakage, and inefficient fan operation can increase auxiliary power consumption, restrict plant capacity, and reduce the performance of connected equipment.",
      "MACPROTEC applies advanced CFD simulations to evaluate flow distribution, pressure loss, system resistance, and fan operating behavior under actual plant conditions. Our analyses identify aerodynamic bottlenecks, improve duct layouts, support fan selection or upgrades, and optimize overall gas handling performance for greater efficiency and reliability.",
    ],
    applications: [
      "ID, FD & PA Fan Systems",
      "Boiler Air Ducts",
      "Flue Gas Duct Networks",
      "ESP & Baghouse Ducting",
      "SCR & FGD Duct Systems",
      "HRSG Gas Paths",
      "Chimney & Stack Connections",
      "Waste Heat Recovery Ducts",
    ],
    keyAnalyses: [
      "Velocity and pressure distribution analysis",
      "Static and total pressure drop evaluation",
      "Fan operating point and system resistance assessment",
      "Duct branch flow balancing",
      "Flow separation and recirculation identification",
      "High-velocity and localized loss assessment",
      "Air leakage and bypass flow investigation",
      "Fan inlet and outlet flow quality evaluation",
      "Duct modification and retrofit scenario analysis",
    ],
    deliverables: [
      "Velocity, pressure, and streamline visualizations",
      "Duct pressure loss and system resistance assessment",
      "Fan operating point and performance evaluation",
      "Flow imbalance and bottleneck identification",
      "Local loss and high-velocity zone assessment",
      "Comparative evaluation of duct modifications",
      "Engineering recommendations for fan and duct optimization",
    ],
    keyBenefits: [
      "Reduce fan power consumption and auxiliary load",
      "Minimize pressure losses across gas handling systems",
      "Improve airflow and flue gas distribution",
      "Increase fan operating efficiency and stability",
      "Eliminate aerodynamic bottlenecks and flow imbalance",
      "Improve performance of downstream equipment",
      "Support plant debottlenecking and capacity increases",
      "Reduce operating costs and improve overall plant efficiency",
    ],
  },
  {
    id: "08",
    slug: "root-cause-investigation",
    title: "Root Cause CFD Investigation",
    badge: "TROUBLESHOOTING & DIAGNOSTICS",
    image: "/images/power/service-08.jpg",
    shortDescription:
      "Recreating actual power plant operating conditions through physics simulation to pinpoint the root cause of pressure drop, fouling, erosion, or combustion instability.",
    description: [
      "Persistent performance problems in power generation systems are often caused by complex interactions between fluid flow, pressure, temperature, combustion, and particle behavior that cannot be fully identified through conventional plant measurements alone. Problems such as unexplained pressure losses, temperature imbalance, unstable combustion, ash deposition, erosion, and inadequate gas distribution can reduce plant output and lead to recurring equipment failures.",
      "MACPROTEC applies advanced CFD simulations to recreate actual operating conditions and investigate the physical mechanisms behind these problems. By combining plant operating data with detailed flow, thermal, combustion, and multiphase analysis, we identify the underlying cause of performance limitations and evaluate corrective solutions before modifications are implemented in the plant.",
    ],
    applications: [
      "Boiler Performance Problems",
      "Combustion Instability",
      "Abnormal Pressure Loss",
      "Temperature Imbalance",
      "Ash Deposition & Fouling",
      "Tube & Duct Erosion",
      "Flow Distribution Problems",
      "Fan & Gas Path Limitations",
    ],
    keyAnalyses: [
      "Flow and pressure anomaly investigation",
      "Temperature imbalance and hot spot analysis",
      "Combustion instability and fuel-air distribution assessment",
      "Flow separation, recirculation, and dead zone identification",
      "Ash deposition, fouling, and particle accumulation analysis",
      "Erosion and localized high-velocity investigation",
      "Fan and gas-path bottleneck assessment",
      "Comparison of actual versus expected operating conditions",
      "Evaluation of corrective modifications and operating scenarios",
    ],
    deliverables: [
      "Root cause investigation report",
      "CFD flow, pressure, and temperature visualizations",
      "Identification of performance-limiting mechanisms",
      "Quantification of pressure, thermal, or flow abnormalities",
      "Comparative assessment of corrective alternatives",
      "Engineering recommendations for remedial modifications",
      "Technical implementation guidance and supporting CFD results",
    ],
    keyBenefits: [
      "Identify the underlying cause of recurring plant problems",
      "Reduce troubleshooting time and unnecessary modifications",
      "Eliminate performance bottlenecks and operational limitations",
      "Reduce unplanned shutdowns and production losses",
      "Improve equipment reliability and service life",
      "Validate corrective actions before plant implementation",
      "Reduce maintenance and operating costs",
      "Improve long-term plant efficiency and operational stability",
    ],
  },
];
