export interface SteelService {
  id: string;
  slug: string;
  title: string;
  badge: string;
  image: string;
  shortDescription: string;
  description: string[];
  applications: string[];
  keyAnalyses: string[];
  deliverables: string[];
  keyBenefits: string[];
}

export const STEEL_SERVICES: SteelService[] = [
  {
    id: "01",
    slug: "flow-and-pressure-analysis",
    title: "Flow & Pressure CFD Analysis",
    badge: "FLUID DYNAMICS",
    image: "/images/steel/service-01.jpg",
    shortDescription:
      "Gas and fluid flow modeling across blast furnaces, BOF/EAF gas systems, duct networks, and stacks to eliminate hydraulic bottlenecks and balance draft systems.",
    description: [
      "Steel manufacturing involves the transportation of high-temperature process gases through furnaces, duct networks, gas cleaning systems, cyclones, stacks, and waste heat recovery units. Poor flow distribution, excessive pressure losses, and flow recirculation can significantly impact process efficiency, increase fan power consumption, and reduce equipment performance.",
      "MACPROTEC applies advanced CFD simulations to evaluate gas flow behavior, pressure distribution, velocity profiles, and flow uniformity throughout steel plant systems. Our engineering studies identify hydraulic bottlenecks, optimize gas transport systems, improve process stability, and support design modifications that enhance productivity, energy efficiency, and operational reliability.",
    ],
    applications: [
      "Blast Furnace (BF) gas flow systems",
      "Basic Oxygen Furnace (BOF) off-gas systems",
      "Electric Arc Furnace (EAF) exhaust systems",
      "Reheating and Annealing Furnaces",
      "Hot Blast Stove gas distribution",
      "Duct and Manifold Networks",
      "Cyclones and Gas Cleaning Systems",
      "Bag Filters and Dust Collection Systems",
      "Waste Heat Recovery (WHR) gas ducts",
      "Chimneys, Stacks, and Exhaust Systems",
    ],
    keyAnalyses: [
      "Gas flow and velocity distribution analysis",
      "Static and total pressure drop evaluation",
      "Flow balancing in duct and manifold systems",
      "Identification of flow separation, recirculation, and dead zones",
      "Fan operating point and system resistance assessment",
      "Air leakage (false air) and gas bypass investigation",
      "Flow optimization for gas cleaning and exhaust systems",
      "Evaluation of design modifications before implementation",
    ],
    deliverables: [
      "CFD flow and pressure contour plots",
      "Velocity vectors and streamline visualizations",
      "Pressure drop and flow distribution reports",
      "Fan and duct performance assessment",
      "Engineering recommendations for system optimization",
      "Design modification assessment and comparison",
      "Comprehensive technical report with actionable solutions",
    ],
    keyBenefits: [
      "Reduce pressure losses and fan power consumption",
      "Improve gas extraction and process stability",
      "Eliminate flow bottlenecks and dead zones",
      "Increase equipment and system efficiency",
      "Improve flow uniformity across process equipment",
      "Reduce operational risks and unplanned downtime",
      "Support engineering decisions through virtual design validation",
      "Improve overall plant reliability while lowering operating costs",
    ],
  },
  {
    id: "02",
    slug: "thermal-and-heat-transfer-analysis",
    title: "Thermal & Heat Transfer Analysis",
    badge: "THERMAL & ENERGY",
    image: "/images/steel/service-02.jpg",
    shortDescription:
      "Evaluation of heat transfer mechanisms, temperature distribution, thermal radiation, and cooling performance across critical steel plant equipment.",
    description: [
      "Efficient heat transfer is fundamental to steel manufacturing, directly influencing fuel consumption, product quality, equipment life, and process stability. Uneven temperature distribution, excessive heat losses, refractory hot spots, and inadequate cooling can lead to reduced production efficiency, increased operating costs, and premature equipment failure.",
      "MACPROTEC utilizes advanced CFD simulations to evaluate heat transfer mechanisms, temperature distribution, thermal radiation, and cooling performance across critical steel plant equipment. Our analyses help optimize furnace operation, improve thermal efficiency, reduce energy losses, and support engineering decisions for process improvements and equipment upgrades.",
    ],
    applications: [
      "Blast Furnace thermal performance",
      "Basic Oxygen Furnace (BOF)",
      "Electric Arc Furnace (EAF)",
      "Reheating and Annealing Furnaces",
      "Hot Blast Stoves",
      "Continuous Casting Cooling Systems",
      "Waste Heat Recovery Systems",
      "Ladles and Tundishes",
      "Furnace Walls and Refractory Systems",
      "Heat Exchangers and Cooling Equipment",
    ],
    keyAnalyses: [
      "Temperature distribution and thermal mapping",
      "Heat transfer and thermal radiation analysis",
      "Identification of heat loss and thermal leakage",
      "Refractory thermal performance evaluation",
      "Cooling system effectiveness assessment",
      "Thermal uniformity and hot spot identification",
      "Transient heating and cooling simulations",
      "Evaluation of thermal design modifications",
    ],
    deliverables: [
      "Temperature contour and thermal distribution plots",
      "Heat flux and thermal radiation analysis reports",
      "Hot spot and thermal loss identification",
      "Cooling performance assessment",
      "Engineering recommendations for thermal optimization",
      "Comparative evaluation of design improvements",
      "Comprehensive technical report with actionable recommendations",
    ],
    keyBenefits: [
      "Improve thermal efficiency and fuel utilization",
      "Reduce heat losses and operating costs",
      "Eliminate thermal hot spots and uneven heating",
      "Extend refractory and equipment service life",
      "Improve product quality through uniform temperature distribution",
      "Increase process stability and production reliability",
      "Support engineering decisions through virtual thermal validation",
      "Reduce maintenance requirements and unplanned shutdowns",
    ],
  },
  {
    id: "03",
    slug: "combustion-cfd-analysis",
    title: "Combustion CFD Analysis",
    badge: "COMBUSTION & FUELS",
    image: "/images/steel/service-03.jpg",
    shortDescription:
      "Advanced modeling of flame behavior, fuel-air mixing, species concentration, emissions, and thermal heat release in steel plant furnaces.",
    description: [
      "Efficient combustion is essential for achieving high thermal efficiency, stable furnace operation, and consistent steel quality. Poor fuel-air mixing, flame instability, uneven temperature distribution, and incomplete combustion can increase fuel consumption, emissions, refractory wear, and process variability.",
      "MACPROTEC applies advanced CFD simulations to analyze combustion processes within steel plant furnaces and thermal systems. By modeling flame behavior, fuel-air mixing, heat release, species concentration, and combustion efficiency, we help optimize burner performance, reduce emissions, improve fuel utilization, and enhance overall process reliability.",
    ],
    applications: [
      "Blast Furnace tuyere combustion",
      "Basic Oxygen Furnace (BOF)",
      "Electric Arc Furnace (EAF) burner systems",
      "Reheating Furnaces",
      "Walking Beam Furnaces",
      "Hot Blast Stoves",
      "Direct Reduced Iron (DRI) Furnaces",
      "Ladle Preheating Furnaces",
      "Heat Treatment Furnaces",
      "Alternative Fuel and Fuel Conversion Studies",
    ],
    keyAnalyses: [
      "Flame shape, stability, and length analysis",
      "Fuel-air mixing and combustion efficiency evaluation",
      "Temperature and heat release distribution",
      "Oxygen concentration and excess air assessment",
      "Species concentration (CO, CO₂, O₂, NOx) analysis",
      "Burner performance and flame impingement evaluation",
      "Alternative fuel combustion assessment",
      "Evaluation of burner and furnace design modifications",
    ],
    deliverables: [
      "Flame and temperature contour visualizations",
      "Species concentration and combustion efficiency reports",
      "Fuel-air mixing and burner performance assessment",
      "Emission prediction and combustion analysis",
      "Engineering recommendations for combustion optimization",
      "Comparative evaluation of burner and fuel configurations",
      "Comprehensive technical report with actionable recommendations",
    ],
    keyBenefits: [
      "Improve combustion efficiency and fuel utilization",
      "Reduce fuel consumption and operating costs",
      "Lower CO, NOx, and other combustion-related emissions",
      "Enhance flame stability and furnace performance",
      "Improve temperature uniformity and product quality",
      "Extend burner and refractory service life",
      "Support fuel conversion and alternative fuel implementation",
      "Increase process reliability while reducing operational risks",
    ],
  },
  {
    id: "04",
    slug: "multiphase-and-gas-solid-flow-analysis",
    title: "Multiphase & Gas-Solid Flow Analysis",
    badge: "MULTIPHASE FLOW",
    image: "/images/steel/service-04.jpg",
    shortDescription:
      "Coupled CFD-multiphase modeling to simulate gas-solid interaction, particle trajectories, erosion patterns, and pneumatic transport across steel production.",
    description: [
      "Steel manufacturing processes involve complex interactions between gases, solid particles, molten materials, and injected fuels. Accurate prediction of gas-solid flow behavior is essential for improving process efficiency, minimizing material losses, reducing equipment wear, and ensuring stable plant operation. Poor particle distribution, erosion, dust accumulation, and uneven material transport can significantly impact production performance and maintenance costs.",
      "MACPROTEC utilizes advanced CFD coupled with multiphase flow models to simulate the interaction between gases and solid particles throughout steel production processes. Our analyses provide detailed insights into particle trajectories, material distribution, erosion patterns, dust transport, and pneumatic conveying performance, enabling optimized equipment design and reliable plant operation.",
    ],
    applications: [
      "Pulverized Coal Injection (PCI) Systems",
      "Blast Furnace burden and gas flow",
      "Cyclones and Gas Cleaning Systems",
      "Dust Collection and Bag Filter Systems",
      "Sinter Plant Gas-Solid Flow",
      "Pneumatic Conveying Systems",
      "Material Transfer Chutes and Hoppers",
      "Iron Ore, Coke, and Lime Handling Systems",
      "Dust Extraction Duct Networks",
      "Waste Material and Ash Handling Systems",
    ],
    keyAnalyses: [
      "Gas-solid flow distribution analysis",
      "Particle trajectory and residence time prediction",
      "Particle separation and collection efficiency",
      "Erosion and wear assessment",
      "Dust transport and deposition analysis",
      "Pneumatic conveying performance evaluation",
      "Particle concentration and dispersion analysis",
      "Evaluation of design modifications for improved flow performance",
    ],
    deliverables: [
      "Gas-solid flow and particle trajectory visualizations",
      "Particle concentration and residence time reports",
      "Erosion and wear prediction maps",
      "Dust collection efficiency assessment",
      "Pneumatic conveying performance analysis",
      "Engineering recommendations for system optimization",
      "Comprehensive technical report with actionable recommendations",
    ],
    keyBenefits: [
      "Improve gas-solid flow efficiency and process stability",
      "Reduce equipment erosion and maintenance costs",
      "Increase dust collection and separation efficiency",
      "Minimize material losses and product contamination",
      "Optimize pneumatic conveying and material handling systems",
      "Improve equipment reliability and service life",
      "Support design improvements through virtual engineering validation",
      "Reduce operating costs while enhancing overall plant performance",
    ],
  },
  {
    id: "05",
    slug: "dust-collection-and-separation-analysis",
    title: "Dust Collection & Separation Analysis",
    badge: "ENVIRONMENTAL & DUST",
    image: "/images/steel/service-05.jpg",
    shortDescription:
      "CFD analysis of airflow, particle behavior, and separation efficiency in baghouses, ESPs, and cyclones to lower emissions and pressure drop.",
    description: [
      "Effective dust collection and gas cleaning systems are essential for maintaining environmental compliance, protecting equipment, and ensuring safe and efficient steel plant operation. Poor flow distribution, particle re-entrainment, excessive pressure losses, and inefficient dust separation can increase emissions, reduce equipment performance, and lead to higher operating and maintenance costs.",
      "MACPROTEC applies advanced CFD simulations to evaluate airflow, particle behavior, and separation efficiency within dust collection and gas cleaning systems. Our analyses help optimize gas distribution, improve dust capture efficiency, reduce pressure losses, and enhance the overall performance of pollution control equipment across steel manufacturing facilities.",
    ],
    applications: [
      "Bag Filter (Baghouse) Systems",
      "Electrostatic Precipitators (ESP)",
      "Cyclone Separators",
      "Blast Furnace Gas Cleaning Systems",
      "Basic Oxygen Furnace (BOF) Dust Collection",
      "Electric Arc Furnace (EAF) Fume Collection",
      "Secondary Fume Extraction Systems",
      "Dust Collection Duct Networks",
      "Material Handling Dust Extraction Systems",
      "Stack and Exhaust Emission Systems",
    ],
    keyAnalyses: [
      "Airflow distribution and flow balancing analysis",
      "Dust particle transport and separation efficiency",
      "Pressure drop and system resistance evaluation",
      "Particle deposition and re-entrainment assessment",
      "Filter loading and gas distribution analysis",
      "Cyclone and separator performance evaluation",
      "Dust leakage and bypass flow investigation",
      "Evaluation of system upgrades and design modifications",
    ],
    deliverables: [
      "Airflow and particle distribution visualizations",
      "Dust separation efficiency assessment",
      "Pressure drop and system performance reports",
      "Particle deposition and dust accumulation analysis",
      "Engineering recommendations for system optimization",
      "Comparative evaluation of alternative designs",
      "Comprehensive technical report with actionable recommendations",
    ],
    keyBenefits: [
      "Improve dust collection and separation efficiency",
      "Reduce particulate emissions and ensure environmental compliance",
      "Lower pressure losses and fan power consumption",
      "Extend filter, cyclone, and equipment service life",
      "Minimize dust leakage and maintenance requirements",
      "Improve process reliability and workplace safety",
      "Optimize pollution control system performance",
      "Reduce operating costs through improved system efficiency",
    ],
  },
  {
    id: "06",
    slug: "industrial-ventilation-and-fume-extraction",
    title: "Industrial Ventilation & Fume Extraction CFD Analysis",
    badge: "SAFETY & VENTILATION",
    image: "/images/steel/service-06.jpg",
    shortDescription:
      "Simulation of airflow patterns, fume dispersion, and exhaust hood efficiency to ensure worker safety, regulatory compliance, and thermal comfort.",
    description: [
      "Effective ventilation and fume extraction systems are critical for maintaining safe working conditions, ensuring environmental compliance, and protecting equipment in steel manufacturing facilities. Inefficient fume capture, poor airflow distribution, and inadequate ventilation can result in hazardous gas accumulation, excessive dust emissions, heat build-up, and increased energy consumption.",
      "MACPROTEC utilizes advanced CFD simulations to evaluate airflow patterns, fume dispersion, ventilation effectiveness, and exhaust system performance throughout steel plants. Our engineering analyses optimize hood design, extraction systems, duct networks, and fan performance to improve contaminant capture, enhance worker safety, and maximize energy efficiency.",
    ],
    applications: [
      "Electric Arc Furnace (EAF) Fume Extraction",
      "Basic Oxygen Furnace (BOF) Ventilation Systems",
      "Secondary Fume Extraction Systems",
      "Blast Furnace Cast House Ventilation",
      "Reheating Furnace Exhaust Systems",
      "Ladle Furnace Fume Extraction",
      "Continuous Casting Ventilation",
      "Rolling Mill Ventilation Systems",
      "Material Handling Dust Extraction",
      "General Plant and Workshop Ventilation",
    ],
    keyAnalyses: [
      "Airflow distribution and ventilation effectiveness",
      "Fume capture and extraction efficiency analysis",
      "Smoke and contaminant dispersion simulation",
      "Hood design and extraction system optimization",
      "Pressure drop and duct network performance evaluation",
      "Fan performance and airflow balancing analysis",
      "Heat accumulation and thermal comfort assessment",
      "Evaluation of ventilation system upgrades and design modifications",
    ],
    deliverables: [
      "Airflow, velocity, and fume dispersion visualizations",
      "Ventilation and fume capture efficiency assessment",
      "Pressure drop and duct system performance reports",
      "Hood and extraction system optimization recommendations",
      "Fan and ventilation network performance analysis",
      "Comparative evaluation of design alternatives",
      "Comprehensive technical report with actionable recommendations",
    ],
    keyBenefits: [
      "Improve fume capture and extraction efficiency",
      "Enhance workplace safety and air quality",
      "Reduce employee exposure to dust, fumes, and hazardous gases",
      "Lower ventilation energy consumption through optimized airflow",
      "Improve compliance with environmental and occupational safety standards",
      "Reduce heat accumulation in production areas",
      "Increase reliability of ventilation and exhaust systems",
      "Support cost-effective design improvements through virtual engineering validation",
    ],
  },
  {
    id: "07",
    slug: "material-handling-and-pneumatic-conveying",
    title: "Material Handling & Pneumatic Conveying CFD",
    badge: "MATERIAL TRANSPORT",
    image: "/images/steel/service-07.jpg",
    shortDescription:
      "Multiphase flow simulation of gas-solid transport, particle behavior, pipeline erosion, and material flow characteristics in bulk handling operations.",
    description: [
      "Efficient material handling and pneumatic conveying systems are essential for the reliable transport of raw materials, fuels, additives, and dust throughout steel manufacturing facilities. Inadequate flow distribution, excessive pressure losses, pipeline erosion, material blockage, and particle segregation can reduce system capacity, increase maintenance requirements, and disrupt production.",
      "MACPROTEC applies advanced CFD and multiphase flow simulations to evaluate gas-solid transport, particle behavior, conveying efficiency, and material flow characteristics. Our engineering analyses help optimize conveying systems, minimize wear, eliminate flow restrictions, and improve the reliability and efficiency of bulk material handling operations.",
    ],
    applications: [
      "Pulverized Coal Injection (PCI) Systems",
      "Lime and Flux Pneumatic Conveying",
      "Iron Ore Fines Conveying Systems",
      "Coke Breeze Transport Systems",
      "Dust Collection and Dust Recycling Systems",
      "Material Transfer Chutes and Feed Hoppers",
      "Silo Filling and Discharge Systems",
      "Dense and Dilute Phase Pneumatic Conveying",
      "Bulk Material Storage and Distribution Networks",
      "Ash and By-product Handling Systems",
    ],
    keyAnalyses: [
      "Gas-solid conveying flow analysis",
      "Particle velocity and trajectory prediction",
      "Pressure drop and conveying capacity evaluation",
      "Pipeline erosion and wear assessment",
      "Material deposition and blockage investigation",
      "Particle segregation and flow uniformity analysis",
      "Hopper, chute, and silo discharge performance evaluation",
      "Assessment of design modifications for improved conveying efficiency",
    ],
    deliverables: [
      "Gas-solid flow and particle trajectory visualizations",
      "Pressure drop and conveying performance reports",
      "Pipeline erosion and wear prediction maps",
      "Material distribution and blockage assessment",
      "Engineering recommendations for system optimization",
      "Comparative evaluation of alternative conveying designs",
      "Comprehensive technical report with actionable recommendations",
    ],
    keyBenefits: [
      "Improve material transport efficiency and system reliability",
      "Reduce pipeline erosion and maintenance costs",
      "Minimize material blockage and unplanned downtime",
      "Optimize conveying capacity while reducing pressure losses",
      "Improve bulk material flow uniformity and handling performance",
      "Extend the service life of pipelines and conveying equipment",
      "Support design improvements through virtual engineering validation",
      "Reduce operating costs while enhancing overall plant productivity",
    ],
  },
  {
    id: "08",
    slug: "fan-and-duct-system-optimization",
    title: "Fan & Duct System Optimization",
    badge: "FAN & DUCT DYNAMICS",
    image: "/images/steel/service-08.jpg",
    shortDescription:
      "CFD analysis of airflow distribution, pressure losses, fan operating points, and duct system behavior to cut power consumption and balance draft.",
    description: [
      "Fan and duct systems play a vital role in transporting process gases, extracting fumes, recovering waste heat, and maintaining pressure balance throughout steel manufacturing facilities. Inefficient duct layouts, excessive pressure losses, flow imbalance, air leakage, and improperly selected fans can significantly increase energy consumption, reduce process efficiency, and limit plant capacity.",
      "MACPROTEC utilizes advanced CFD simulations to evaluate airflow distribution, pressure losses, fan performance, and duct system behavior under actual operating conditions. Our engineering analyses identify hydraulic bottlenecks, optimize duct geometry, improve fan operating efficiency, and enhance overall gas transport performance while minimizing energy consumption and operating costs.",
    ],
    applications: [
      "Blast Furnaces",
      "BOF & EAF Gas Systems",
      "Reheating Furnaces",
      "Baghouses & Dust Collectors",
      "Waste Heat Recovery Systems",
      "Industrial Ventilation",
      "Process Duct Networks",
      "Exhaust & Stack Systems",
    ],
    keyAnalyses: [
      "Airflow and velocity distribution analysis",
      "Pressure drop and system resistance evaluation",
      "Fan operating point and performance assessment",
      "Duct sizing and layout optimization",
      "Flow balancing across multiple duct branches",
      "Air leakage (false air) and gas bypass investigation",
      "Identification of recirculation zones and flow separation",
      "Evaluation of fan and duct design modifications",
    ],
    deliverables: [
      "Airflow, velocity, and pressure contour visualizations",
      "Pressure loss and duct system performance reports",
      "Fan performance and operating point assessment",
      "Flow balancing and system optimization recommendations",
      "Comparative evaluation of design alternatives",
      "Energy-saving and capacity improvement recommendations",
      "Comprehensive technical report with actionable engineering solutions",
    ],
    keyBenefits: [
      "Reduce fan power consumption and operating costs",
      "Minimize pressure losses throughout the duct network",
      "Improve gas transport and extraction efficiency",
      "Eliminate flow imbalance and hydraulic bottlenecks",
      "Increase fan reliability and equipment service life",
      "Support plant debottlenecking and capacity expansion",
      "Optimize existing systems before capital investment",
      "Improve overall process stability and energy efficiency",
    ],
  },
  {
    id: "09",
    slug: "equipment-performance-optimization",
    title: "Equipment Performance Optimization",
    badge: "ASSET OPTIMIZATION",
    image: "/images/steel/service-09.jpg",
    shortDescription:
      "Aerodynamic, thermal, and fluid dynamic evaluation of critical steel process equipment to debottleneck operations without production shutdown.",
    description: [
      "Steel manufacturing equipment operates under demanding thermal, fluid flow, and process conditions where even minor inefficiencies can lead to increased energy consumption, reduced throughput, excessive wear, and higher operating costs. Identifying performance limitations through physical testing alone is often costly and disruptive to production.",
      "MACPROTEC leverages advanced CFD simulations to evaluate the aerodynamic, thermal, and fluid dynamic performance of critical process equipment. Our engineering analyses identify operational bottlenecks, optimize process conditions, validate design improvements, and enhance equipment efficiency without interrupting plant operations.",
    ],
    applications: [
      "Blast Furnaces",
      "Basic Oxygen Furnaces (BOF)",
      "Electric Arc Furnaces (EAF)",
      "Reheating Furnaces",
      "Hot Blast Stoves",
      "Cyclones & Separators",
      "Baghouses & Dust Collectors",
      "Waste Heat Recovery Systems",
    ],
    keyAnalyses: [
      "Equipment performance and efficiency assessment",
      "Flow distribution and process uniformity analysis",
      "Pressure loss and hydraulic resistance evaluation",
      "Thermal performance and heat transfer analysis",
      "Identification of operational bottlenecks",
      "Equipment debottlenecking and capacity assessment",
      "Evaluation of retrofit and design modifications",
      "Performance comparison under multiple operating scenarios",
    ],
    deliverables: [
      "Equipment performance evaluation report",
      "CFD flow, pressure, and temperature visualizations",
      "Bottleneck identification and root cause assessment",
      "Capacity improvement and debottlenecking recommendations",
      "Comparative evaluation of design alternatives",
      "Energy-saving and process optimization recommendations",
      "Comprehensive technical report with actionable engineering solutions",
    ],
    keyBenefits: [
      "Improve equipment efficiency and process performance",
      "Increase plant throughput and production capacity",
      "Reduce energy consumption and operating costs",
      "Eliminate process bottlenecks and flow restrictions",
      "Extend equipment service life and reliability",
      "Support retrofit decisions through virtual engineering validation",
      "Minimize operational risks before implementation",
      "Enhance overall plant productivity and process stability",
    ],
  },
  {
    id: "10",
    slug: "root-cause-investigation",
    title: "Root Cause Investigation",
    badge: "TROUBLESHOOTING & DIAGNOSTICS",
    image: "/images/steel/service-10.jpg",
    shortDescription:
      "Virtual recreation of actual operating conditions to pinpoint physical mechanisms causing pressure loss, thermal anomalies, dust build-up, or equipment wear.",
    description: [
      "Recurring operational issues such as excessive pressure losses, poor gas distribution, abnormal temperature profiles, dust accumulation, equipment wear, and unstable process performance are often symptoms of underlying flow-related problems that are difficult to identify through conventional inspections alone. Determining the true root cause is essential for implementing effective and sustainable solutions.",
      "MACPROTEC applies advanced CFD simulations to investigate complex fluid flow, heat transfer, and multiphase phenomena within steel manufacturing processes. By recreating actual operating conditions, we identify the physical mechanisms responsible for performance issues, validate engineering hypotheses, and recommend targeted modifications that eliminate the root cause rather than treating the symptoms.",
    ],
    applications: [
      "Blast Furnaces",
      "Basic Oxygen Furnaces (BOF)",
      "Electric Arc Furnaces (EAF)",
      "Reheating Furnaces",
      "Gas Cleaning Systems",
      "Fan & Duct Networks",
      "Dust Collection Systems",
      "Waste Heat Recovery Systems",
    ],
    keyAnalyses: [
      "Root cause identification through CFD simulation",
      "Flow distribution and pressure imbalance analysis",
      "Temperature distribution and thermal anomaly assessment",
      "Air leakage (false air) and gas bypass investigation",
      "Flow recirculation and dead zone identification",
      "Dust accumulation and erosion analysis",
      "Evaluation of operational and design modifications",
      "Comparative assessment of alternative engineering solutions",
    ],
    deliverables: [
      "Root cause investigation report",
      "CFD flow, pressure, and temperature visualizations",
      "Identification of performance-limiting factors",
      "Engineering recommendations with corrective actions",
      "Comparative evaluation of proposed solutions",
      "Risk assessment of recommended modifications",
      "Comprehensive technical report with implementation guidance",
    ],
    keyBenefits: [
      "Identify the true cause of recurring operational problems",
      "Eliminate process bottlenecks and performance limitations",
      "Reduce troubleshooting time and maintenance costs",
      "Improve equipment reliability and process stability",
      "Minimize production losses and unplanned downtime",
      "Support data-driven engineering decisions",
      "Validate solutions before plant implementation",
      "Improve long-term plant efficiency and operational performance",
    ],
  },
];
